[package]
name = "mago-spike"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
mago-syntax = { path = "../../../mago/crates/syntax" }
mago-allocator = { path = "../../../mago/crates/allocator" }
mago-span = { path = "../../../mago/crates/span" }
mago-database = { path = "../../../mago/crates/database" }
walkdir = "2"

[profile.release]
debug = false
