//! The `steins` binary.
//!
//! Two commands exist for this milestone (ADR-0020 documents the eventual
//! six-command surface; the rest are deliberately NOT stubbed). `check` walks
//! `.php` files, runs the salsa pipeline, prints proof-layer diagnostics, and
//! exits 1 if any finding was reported. `annotate` reprints a single file with a
//! right-margin column of *proven* inferred facts (the Rigor-style display).

// The output seam (issue #44) is declared FIRST and `#[macro_use]`d: `outln!` /
// `out!` / `errln!` are `macro_rules!` macros, which are textually scoped, so
// every module that writes a byte has to come after this line.
#[macro_use]
mod out;

mod baseline;
mod doctor;
mod effect_baseline;
mod sha256;

// The profile engine (Surface, the rung ladder, user-profile resolution) moved to
// `steins_infer::profile` so the wasm playground and the CLI read ONE
// implementation (the no-second-relation discipline, applied to surface
// selection). The alias keeps every `profile::` path in this crate unchanged.
pub(crate) use steins_infer::profile;

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use steins_db::{
    PluginFacts, Project, ProjectLayout, SourceFile, SteinsDatabase, composer,
    parse as parse_tree,
};
use steins_edit::{
    PartitionMap, TransformReport, VouchSet, plan_phpdoc_honesty, plan_phpdoc_to_native,
    unified_diff,
};
use steins_infer::{
    Diagnostic, EffectSummary, LineFact, NoFold, SOUND_SUBSET_NOTICE, SidecarFolder,
    annotate_file, annotate_project, apply_inline_ignores, check_project,
    check_project_with_runtime, effect_summaries_file, effect_summaries_project,
};
use steins_syntax::SourceTree;

#[derive(Clone, Copy, PartialEq, Eq)]
enum Format {
    Text,
    Json,
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    // Every command's verdict passes through the output seam on its way out
    // (issue #44): `out::finish` flushes stdout and decides what a failed write
    // does to the exit code. A closed reader leaves `code` alone — see `out`.
    out::finish(dispatch(&args))
}

/// Dispatch on the subcommand. Split out of `main` so there is exactly one exit
/// path through [`out::finish`] rather than one per `return`.
fn dispatch(args: &[String]) -> ExitCode {
    match args.first().map(String::as_str) {
        Some("check") => run_check(&args[1..]),
        Some("annotate") => run_annotate(&args[1..]),
        Some("transform") => run_transform(&args[1..]),
        Some("effect-diff") => run_effect_diff(&args[1..]),
        Some("doctor") => doctor::run_doctor(&args[1..]),
        Some("version" | "--version" | "-v") => print_version(),
        Some("license" | "licenses") => print_license(),
        Some(other) => {
            errln!(
                "steins: unknown command `{other}` (available: check, annotate, transform, effect-diff, doctor, version, license)"
            );
            ExitCode::from(2)
        }
        None => {
            errln!(
                "usage: steins check [--format text|json] [--profile <name>] [--no-php] [--vendor-diagnostics] [--set-baseline] [--baseline <path>] [--ignore-baseline] <paths...>"
            );
            errln!("       steins annotate [--no-php] [--format text|json] <file.php>");
            errln!(
                "       steins transform <phpdoc-to-native|phpdoc-honesty> [--apply] [--format text|json] <paths...>"
            );
            errln!(
                "       steins effect-diff [--baseline <path>] [--set-baseline] [--format text|json] <paths...>"
            );
            errln!("       steins doctor [--no-php] [--baseline <path>] [path]");
            errln!("       steins version | -v | --version");
            errln!("       steins license");
            ExitCode::from(2)
        }
    }
}

/// Steins' own terms, embedded (#43). The release archive ships `LICENSE`
/// beside the binary, but nothing downstream guarantees the two stay together:
/// the Homebrew formula installs the executable and the third-party notices and
/// **not** this file, and `cargo install --git` produces a bare binary. Apache-2.0
/// §4(a) requires a recipient to get a copy of the License, so the binary carries
/// one rather than depending on a packager to.
const LICENSE_APACHE: &str = include_str!("../../../LICENSE");

/// The bundled dependencies' notices, embedded for the same reason — their
/// MIT/BSD/ISC terms require the notice to accompany a binary distribution.
/// Generated by `cargo xtask licenses`; the CI drift guard keeps it current.
const THIRD_PARTY_LICENSES: &str = include_str!("../../../THIRD-PARTY-LICENSES.md");

/// The `version` banner: what this binary is, which tree it was built from, and
/// where to read the licenses. Build date and revision come from `build.rs` and
/// degrade to `unknown` outside a git working tree.
fn version_text() -> String {
    format!(
        concat!(
            "steins {} ({} revision {}) - {}\n",
            // The holder is the one README's copyright notice states; the crate's
            // `authors` field carries only the individual, so `TypedDuck` is named
            // here rather than silently narrowing the notice.
            "Copyright (c) TypedDuck, {}\n",
            "    Built with the help of many third-party libraries.\n",
            "    Run `steins license` to see all dependencies and their licenses.",
        ),
        env!("CARGO_PKG_VERSION"),
        env!("STEINS_BUILD_DATE"),
        env!("STEINS_GIT_REV"),
        env!("CARGO_PKG_REPOSITORY"),
        env!("CARGO_PKG_AUTHORS"),
    )
}

/// The `license` output: Steins' own Apache-2.0 terms, then every bundled
/// dependency's notice. Both are embedded, so this works for a binary with no
/// accompanying files at all.
///
/// Apache-2.0's text appears twice across the two documents — once as Steins'
/// own terms and once among the dependencies that use it. That is deliberate:
/// `THIRD-PARTY-LICENSES.md` also ships as a standalone file, and a downstream
/// packager may install it *without* `LICENSE` (the Homebrew formula does
/// exactly that), so its Apache-2.0 section has to stand on its own rather than
/// point at a copy that may not be there. Self-sufficiency is a compliance
/// property; non-duplication is only tidiness.
fn license_text() -> String {
    format!(
        "steins {} — open source licenses\n{}\n\n\
         Steins is licensed under the Apache License 2.0:\n\n\
         {}\n\n{THIRD_PARTY_LICENSES}",
        env!("CARGO_PKG_VERSION"),
        env!("CARGO_PKG_REPOSITORY"),
        LICENSE_APACHE.trim_start_matches('\n'),
    )
}

/// `version` / `-v` / `--version`.
fn print_version() -> ExitCode {
    outln!("{}", version_text());
    ExitCode::SUCCESS
}

/// `license` / `licenses`.
fn print_license() -> ExitCode {
    out!("{}", license_text());
    ExitCode::SUCCESS
}

fn run_check(args: &[String]) -> ExitCode {
    let mut format = Format::Text;
    let mut no_php = false;
    let mut set_baseline = false;
    let mut ignore_baseline = false;
    let mut vendor_diagnostics = false;
    let mut baseline_path: Option<String> = None;
    let mut profile_flag: Option<String> = None;
    let mut paths: Vec<String> = Vec::new();
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--no-php" => {
                no_php = true;
                i += 1;
            }
            "--vendor-diagnostics" => {
                vendor_diagnostics = true;
                i += 1;
            }
            "--profile" => {
                let Some(value) = args.get(i + 1) else {
                    errln!("steins: --profile requires a name argument");
                    return ExitCode::from(2);
                };
                profile_flag = Some(value.clone());
                i += 2;
            }
            "--set-baseline" => {
                set_baseline = true;
                i += 1;
            }
            "--ignore-baseline" => {
                ignore_baseline = true;
                i += 1;
            }
            "--baseline" => {
                let Some(value) = args.get(i + 1) else {
                    errln!("steins: --baseline requires a path argument");
                    return ExitCode::from(2);
                };
                baseline_path = Some(value.clone());
                i += 2;
            }
            "--format" => {
                let Some(value) = args.get(i + 1) else {
                    errln!("steins: --format requires an argument (text|json)");
                    return ExitCode::from(2);
                };
                match value.as_str() {
                    "text" => format = Format::Text,
                    "json" => format = Format::Json,
                    other => {
                        errln!("steins: unknown format `{other}` (text|json)");
                        return ExitCode::from(2);
                    }
                }
                i += 2;
            }
            other => {
                paths.push(other.to_owned());
                i += 1;
            }
        }
    }

    if paths.is_empty() {
        errln!("steins: no paths given");
        return ExitCode::from(2);
    }
    if let Err(code) = reject_missing_paths(&paths) {
        return code;
    }

    let mut files = Vec::new();
    for p in &paths {
        collect_php_files(Path::new(p), &mut files);
    }
    files.sort();
    files.dedup();

    // Coverage posture (ADR-0004): with `--no-php` the run is the sound subset,
    // surfaced up front as a startup notice. Without the flag we fold via a
    // lazily-spawned sidecar (spawned only on the first foldable call); if `php`
    // turns out to be unavailable, the folder emits the same notice itself.
    if no_php {
        errln!("{SOUND_SUBSET_NOTICE}");
    }

    // Parse `./steins.toml` ONCE, up front, before any analysis (ADR-0050 §7 /
    // ADR-0052 §5 N2): a malformed file — including an unknown key in `[runtime]`,
    // which `deny_unknown_fields` rejects — is a HARD config error (exit 2), never
    // a warn-and-proceed. Silently proceeding on defaults would let a `warning-hadler`
    // typo leave the safe default in force while the user believed they had overridden
    // it. A missing file is `None` (the built-in defaults govern).
    let config = match read_steins_config() {
        Ok(c) => c,
        Err(e) => {
            errln!("steins: {e}");
            return ExitCode::from(2);
        }
    };
    let (check_cfg, profile_tbl, runtime_cfg, plugin_allow) = match config {
        Some(c) => (c.check, c.profile, c.runtime, allow_list(c.plugins)),
        None => (None, None, None, None),
    };

    // The active display surface (ADR-0050 §5): resolve the selected profile before
    // any analysis so a config error fails fast (exit 2). Precedence: the
    // `--profile` flag beats `[check] profile` beats the built-in `default`.
    let (config_profile, profile_configs) = profiles_from_config(check_cfg, profile_tbl);
    let selected = profile_flag.as_deref().or(config_profile.as_deref());
    let surface = match profile_configs.resolve(selected) {
        Ok(s) => s,
        Err(e) => {
            errln!("steins: {e}");
            return ExitCode::from(2);
        }
    };

    let db = SteinsDatabase::default();
    // One folder for the whole run: it owns the resident sidecar and the fold
    // memo, so a repeated call across files never re-spawns or re-folds.
    let mut folder = if no_php { SidecarFolder::new(true) } else { SidecarFolder::enabled() };

    // Project mode (ADR-0009/0015): all `.php` files across the given paths form
    // ONE project (one salsa DB), so cross-file calls, class chains, and effects
    // resolve. `texts` keeps each file's contents by diagnostic path so the
    // baseline hash can read the flagged line's neighborhood (ADR-0022).
    let mut inputs: Vec<SourceFile> = Vec::new();
    let mut texts: HashMap<String, String> = HashMap::new();
    for file_path in &files {
        let text = match std::fs::read(file_path) {
            Ok(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
            Err(e) => {
                errln!("steins: cannot read {}: {e}", file_path.display());
                continue;
            }
        };
        let path = file_path.to_string_lossy().into_owned();
        texts.insert(path.clone(), text.clone());
        inputs.push(SourceFile::new(&db, path, text));
    }
    let layout = resolve_layout(&paths);
    // The declared target PHP range (issue #28) gates the folder's absence
    // family and curated-fact admission; the checker reads it from the layout.
    folder.set_php_target(layout.php_target().cloned());
    // The plugin channel (ADR-0068), read once at the boundary like the layout.
    let plugins = load_plugins(&layout, plugin_allow.as_deref());
    let project = Project::new(&db, inputs.clone(), layout.clone(), plugins);
    // `[runtime]` pseudo-constants (ADR-0037 §2): the boot truth the checker cannot
    // observe from source (e.g. `warning-handler = "null"`). Parsed above with the
    // rest of the config; an unknown *value* on a known key still warns and keeps the
    // safe default (a parse error already exited 2).
    let (warning_handler_abort, runtime_warnings) = runtime_from_config(runtime_cfg);
    for w in &runtime_warnings {
        errln!("steins: {w}");
    }
    let mut findings: Vec<Diagnostic> = check_project_with_runtime(
        &db,
        project,
        &mut folder,
        warning_handler_abort,
    );

    // Vendor filtering applies FIRST (ADR-0015), before inline ignores and the
    // baseline: vendor code is fully indexed and inferred, but a finding whose
    // path is inside a `vendor/` directory is suppressed by default and never
    // reaches — nor consumes — a later channel (a vendor finding must not eat a
    // baseline entry). `--vendor-diagnostics` opts back in, sending vendor
    // findings through the normal channels like any first-party finding.
    let mut vendor_suppressed = 0usize;
    if !vendor_diagnostics {
        let before = findings.len();
        findings.retain(|d| !layout.is_vendor(&d.path));
        vendor_suppressed = before - findings.len();
    }

    // Profile surface (ADR-0050 §6, second in the pipeline): a finding off the
    // active surface does not exist — it never reaches, nor consumes, a later
    // channel (inline ignore, baseline). This is the M2 adoption-surface core: a
    // bare `check` shows proof + mechanics only; the contract layer opts up via a
    // named profile. Mechanics ids stay on in every profile (anti-rot, §1).
    findings.retain(|d| surface.is_surfaced(d));

    // Scoped policy (ADR-0050 §6, third in the pipeline): `[[policy]]` per-path
    // enable/disable is issue #15 / slice 3. This slice ships the seam as a no-op
    // stage so the composition order is real and slice 3 slots in without moving
    // the earlier stages.
    let findings = apply_policy_stage(findings);

    // Inline `@steins-ignore` applies next (ADR-0023): a finding suppressed
    // inline never reaches — nor consumes — the baseline channel.
    let trees: Vec<&SourceTree> = inputs.iter().map(|&sf| parse_tree(&db, sf)).collect();
    let file_pairs: Vec<(String, &SourceTree)> =
        inputs.iter().zip(trees.iter()).map(|(&sf, &t)| (sf.path(&db).to_owned(), t)).collect();
    let inline = apply_inline_ignores(findings, &file_pairs);

    // Which baseline file to consult (ADR-0022): `--set-baseline` and an explicit
    // `--baseline` both name a file; otherwise the default is auto-loaded when it
    // exists, unless `--ignore-baseline` bypasses it.
    let baseline_file: Option<PathBuf> = if set_baseline {
        Some(PathBuf::from(baseline_path.as_deref().unwrap_or(baseline::DEFAULT_FILE)))
    } else if ignore_baseline {
        None
    } else if let Some(p) = &baseline_path {
        Some(PathBuf::from(p))
    } else if Path::new(baseline::DEFAULT_FILE).exists() {
        Some(PathBuf::from(baseline::DEFAULT_FILE))
    } else {
        None
    };

    if set_baseline {
        let file = baseline_file.expect("set-baseline names a file");
        return write_baseline(&file, &inline.kept, &texts, &surface);
    }

    // Baseline channel: partition the inline survivors into baselined (suppressed,
    // excluded from exit) and reported. `--ignore-baseline` / no file → all report.
    // Staleness is surface-aware (ADR-0050 §8): an unconsumed entry outside the
    // current surface is dormant, not stale. `surface_notice` fires when the active
    // surface exceeds the captured one (the drowns-loudly rule).
    let (reported, baselined, stale, surface_notice) = match &baseline_file {
        Some(file) => match std::fs::read_to_string(file) {
            Ok(text) => match_baseline(file, &text, inline.kept, &texts, &surface),
            Err(_) => (inline.kept, 0, 0, None),
        },
        None => (inline.kept, 0, 0, None),
    };

    // Displayed = object-level survivors + meta-diagnostics (which are exempt from
    // both channels). Sorted for deterministic output.
    let mut displayed = reported;
    displayed.extend(inline.meta);
    displayed.sort_by(|a, b| {
        (a.path.as_str(), a.line, a.column, a.id).cmp(&(b.path.as_str(), b.line, b.column, b.id))
    });

    match format {
        Format::Text => print_text(
            &displayed,
            &surface,
            vendor_suppressed,
            inline.suppressed,
            baselined,
            stale,
            surface_notice.as_deref(),
        ),
        Format::Json => {
            print_json(&displayed, &surface, vendor_suppressed, inline.suppressed, baselined)
        }
    }

    // Exit level (ADR-0050 §7): 1 iff any *fail*-level finding is displayed; a
    // warn-only run exits 0 (that is what `warn` means). Config/usage errors already
    // exited 2 above.
    let any_fail = displayed.iter().any(|d| surface.level(d.id) == profile::Level::Fail);
    if any_fail { ExitCode::FAILURE } else { ExitCode::SUCCESS }
}

/// The `[[policy]]` scoped enable/disable stage (ADR-0050 §6): issue #15 / slice 3.
/// A no-op identity today — the structural seam that keeps the composition order
/// (vendor → surface → policy → inline → baseline) real so slice 3 slots in without
/// disturbing the surrounding stages.
fn apply_policy_stage(findings: Vec<Diagnostic>) -> Vec<Diagnostic> {
    findings
}

/// Write a baseline file from the inline-surviving findings (ADR-0022
/// `--set-baseline`). Never affects exit code: writing is a maintenance action.
/// The header records the capture surface (ADR-0050 §8): the active `surface`'s
/// profile name and resolved id-set, so a later run can tell dormant from stale and
/// notice when its surface exceeds this one.
fn write_baseline(
    file: &Path,
    findings: &[Diagnostic],
    texts: &HashMap<String, String>,
    surface: &profile::Surface,
) -> ExitCode {
    let dir = baseline::base_dir(file);
    let entries: Vec<baseline::Entry> = findings
        .iter()
        // The debug lane (ADR-0053 §4/§8) displays on every profile — `is_surfaced`
        // says so on purpose (a dump is an answered question, always shown) — but
        // must NEVER be captured: `surfaces_id`/`surface_ids` already exclude it
        // from the capture predicate everywhere else, and this filter is what makes
        // that exclusion hold here too. Without it, a committed `\PHPStan\dumpType()`
        // (which reaches `inline.kept` because both the surface stage and the inline
        // channel exempt the debug lane) gets baselined, and a later run reports it
        // as "1 findings in baseline" at exit 0 — a guaranteed runtime fatal frozen
        // green (issue #108).
        .filter(|d| !matches!(steins_infer::layer(d.id), Some(steins_infer::Layer::Debug)))
        .map(|d| {
            let rel = baseline::relativize(&dir, &d.path);
            let hash = texts
                .get(&d.path)
                .map_or_else(String::new, |t| baseline::entry_hash(d.id, &rel, t, d.line));
            // The per-entry capture rung (ADR-0062 A-G10). `None` at the `default`
            // rung, so a default capture writes the pre-S6 bytes exactly.
            baseline::Entry {
                id: d.id.to_owned(),
                path: rel,
                hash,
                surface: baseline::Entry::tag_for(surface.rung()),
            }
        })
        .collect();
    let n = entries.len();
    let capture = baseline::CaptureSurface { profile: surface.name.clone(), ids: surface.surface_ids() };
    match std::fs::write(file, baseline::render(entries, &capture)) {
        Ok(()) => {
            errln!(
                "steins: wrote {n} baseline entries to {} (profile `{}`)",
                file.display(),
                surface.name
            );
            ExitCode::SUCCESS
        }
        Err(e) => {
            errln!("steins: cannot write baseline {}: {e}", file.display());
            ExitCode::from(2)
        }
    }
}

/// Match inline-surviving `findings` against a baseline file's entries. Returns
/// `(reported, baselined_count, stale_count, surface_notice)`.
///
/// Surface-aware (ADR-0050 §8): staleness counts only unconsumed entries whose id
/// is inside the current `surface` (others are dormant — kept silently). The
/// `surface_notice` is `Some` when the active surface admits an id the captured
/// surface (from the header) did not — the "drowns loudly" rule so a
/// `--profile contracts` run over a default-captured baseline says so.
fn match_baseline(
    file: &Path,
    text: &str,
    findings: Vec<Diagnostic>,
    texts: &HashMap<String, String>,
    surface: &profile::Surface,
) -> (Vec<Diagnostic>, usize, usize, Option<String>) {
    let entries = baseline::parse(text);
    let dir = baseline::base_dir(file);
    let mut matcher = baseline::Matcher::new(&entries);
    let mut reported = Vec::new();
    let mut baselined = 0usize;
    for d in findings {
        // The debug lane is exempt from the baseline on the MATCH side too (ADR-0053
        // §4/§8): "never matched by a baseline entry" is symmetric with "never
        // captured" (write_baseline, above). A debug finding must always report even
        // if a stale entry happens to share its `(id, path, hash)` — e.g. a baseline
        // written before this fix, or a hand-edit — so it bypasses the matcher
        // entirely rather than consuming (and hiding behind) such an entry.
        if matches!(steins_infer::layer(d.id), Some(steins_infer::Layer::Debug)) {
            reported.push(d);
            continue;
        }
        let rel = baseline::relativize(&dir, &d.path);
        let hash = texts
            .get(&d.path)
            .map_or_else(String::new, |t| baseline::entry_hash(d.id, &rel, t, d.line));
        if matcher.take(d.id, &rel, &hash) {
            baselined += 1;
        } else {
            reported.push(d);
        }
    }
    // Staleness (§8) folds in the debug-layer carve-out. `surface.surfaces_id`
    // always excludes debug ids (the capture predicate never admits the lane), so
    // reading it alone would call every leftover debug entry *dormant* — kept,
    // never reported, forever. That reading fits an id the active surface simply
    // never looked for; it does not fit a debug entry, which is not "outside this
    // surface" but a mistake that can never become valid again (debug findings now
    // always bypass the matcher, above, so such an entry can never be consumed by
    // any future run either). Folding `Layer::Debug` into the stale predicate
    // surfaces it once, the same way any other stale entry surfaces, so
    // `--set-baseline` clears it instead of it sitting invisible forever.
    let stale = matcher.stale_count_within(surface.rung(), |id| {
        surface.surfaces_id(id) || matches!(steins_infer::layer(id), Some(steins_infer::Layer::Debug))
    });

    // The drowns-loudly notice (ADR-0050 §8): ids the current surface admits that
    // the captured surface did not. A pre-ADR-0050 header (no capture surface) can
    // not be compared, so no notice fires.
    let surface_notice = baseline::parse_header(text).and_then(|captured| {
        let captured_ids: std::collections::HashSet<&str> =
            captured.ids.iter().map(String::as_str).collect();
        let extra = surface
            .surface_ids()
            .into_iter()
            .filter(|id| !captured_ids.contains(id.as_str()))
            .count();
        (extra > 0).then(|| {
            format!(
                "active profile `{}` surfaces {extra} id(s) the baseline (captured under `{}`) did not — \
                 those findings are unbaselined (rerun --set-baseline to capture them)",
                surface.name, captured.profile
            )
        })
    });

    (reported, baselined, stale, surface_notice)
}

/// `steins transform <phpdoc-to-native|phpdoc-honesty> [--apply] [--format
/// text|json] <paths...>` (ADR-0020/0034). Dry-run by default: prints a unified
/// diff and a refusal report, and runs the dual-verification post-check (ADR-0034
/// point 3a — the edited project must produce *zero new diagnostics*). `--apply`
/// writes the edited files only after the post-check passes. Exits 2 on usage
/// error, 1 when the post-check fails, 0 otherwise.
fn run_transform(args: &[String]) -> ExitCode {
    let mut format = Format::Text;
    let mut apply = false;
    let mut subcommand: Option<String> = None;
    let mut paths: Vec<String> = Vec::new();
    let mut config_path: Option<String> = None;
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--apply" => {
                apply = true;
                i += 1;
            }
            "--config" => {
                let Some(value) = args.get(i + 1) else {
                    errln!("steins: --config requires a path argument");
                    return ExitCode::from(2);
                };
                config_path = Some(value.clone());
                i += 2;
            }
            "--format" => {
                let Some(value) = args.get(i + 1) else {
                    errln!("steins: --format requires an argument (text|json)");
                    return ExitCode::from(2);
                };
                match value.as_str() {
                    "text" => format = Format::Text,
                    "json" => format = Format::Json,
                    other => {
                        errln!("steins: unknown format `{other}` (text|json)");
                        return ExitCode::from(2);
                    }
                }
                i += 2;
            }
            other if subcommand.is_none() && !other.starts_with('-') => {
                subcommand = Some(other.to_owned());
                i += 1;
            }
            other => {
                paths.push(other.to_owned());
                i += 1;
            }
        }
    }

    // Select the transform planner by subcommand. `action` is the verb the oracle
    // summary uses for an edited site.
    #[derive(Clone, Copy)]
    enum Kind {
        Promote,
        Honesty,
    }
    let (kind, action) = match subcommand.as_deref() {
        Some("phpdoc-to-native") => (Kind::Promote, "promoted"),
        Some("phpdoc-honesty") => (Kind::Honesty, "rewritten"),
        Some(other) => {
            errln!(
                "steins: unknown transform `{other}` (available: phpdoc-to-native, phpdoc-honesty)"
            );
            return ExitCode::from(2);
        }
        None => {
            errln!(
                "steins: transform requires a name (usage: steins transform <phpdoc-to-native|phpdoc-honesty> [--apply] [--config steins.toml] [--format text|json] <paths...>)"
            );
            return ExitCode::from(2);
        }
    };
    if paths.is_empty() {
        errln!("steins: no paths given");
        return ExitCode::from(2);
    }
    if let Err(code) = reject_missing_paths(&paths) {
        return code;
    }

    // Load the vouching valve (ADR-0046 §2): `steins.toml [transform.vouch]` from
    // `--config`, else `./steins.toml` if present. A malformed entry is a warning,
    // never a hard error (the run proceeds with the well-formed entries).
    let (vouches, vouch_warnings) = load_vouches(config_path.as_deref());
    for w in &vouch_warnings {
        errln!("steins: {w}");
    }

    // Load the region map (ADR-0047 §7): `steins.toml [transform.partitions]`. With
    // no such section this is `None` — the single-region identity, so the transform
    // is byte-identical to a run with no partition config. An *overlap* in the
    // declared partition path-sets is a hard config error (unlike a vouch typo),
    // because a non-disjoint partition claim has no defined region assignment.
    let partitions = match load_partitions(config_path.as_deref()) {
        Ok(p) => p,
        Err(e) => {
            errln!("steins: {e}");
            return ExitCode::from(2);
        }
    };

    let mut files = Vec::new();
    for p in &paths {
        collect_php_files(Path::new(p), &mut files);
    }
    files.sort();
    files.dedup();

    let db = SteinsDatabase::default();
    let mut inputs: Vec<SourceFile> = Vec::new();
    let mut texts: HashMap<String, String> = HashMap::new();
    for file_path in &files {
        let text = match std::fs::read(file_path) {
            Ok(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
            Err(e) => {
                errln!("steins: cannot read {}: {e}", file_path.display());
                continue;
            }
        };
        let path = file_path.to_string_lossy().into_owned();
        texts.insert(path.clone(), text.clone());
        inputs.push(SourceFile::new(&db, path, text));
    }
    let layout = resolve_layout(&paths);
    let plugins = load_plugins(&layout, allow_list_from_disk().as_deref());
    let project = Project::new(&db, inputs.clone(), layout, plugins);

    // Plan the transform (pure — no writes, no re-check).
    // ADR-0047 Slice A: the region map is threaded into the planners but not yet
    // consumed by any decision — the plan is identical with or without it.
    let report = match kind {
        Kind::Promote => plan_phpdoc_to_native(&db, project, &vouches, partitions.as_ref()),
        Kind::Honesty => plan_phpdoc_honesty(&db, project, &vouches, partitions.as_ref()),
    };

    // Vouching an already-benign (or nonexistent) site is a no-op the user should
    // know about (ADR-0046 §2).
    for entry in vouches.unused() {
        errln!("steins: vouched site `{entry}` matched no dynamic-code obstacle (no-op)");
    }

    // Dual verification (ADR-0034 point 3a): re-analyze the edited project and
    // require zero NEW diagnostics vs. the pre-edit baseline. Run in both dry-run
    // and `--apply`, so a violation is visible before anything is written.
    let postcheck = post_check(&db, project, &report, &texts);

    match format {
        Format::Json => print_transform_json(&report, &postcheck, apply && postcheck.ok),
        Format::Text => print_transform_text(&report, &postcheck, &texts, action),
    }

    if !postcheck.ok {
        if apply {
            errln!(
                "steins: post-check found {} new diagnostic(s); refusing to write (ADR-0034)",
                postcheck.new_diagnostics.len()
            );
        }
        return ExitCode::FAILURE;
    }

    if apply {
        let mut written = 0usize;
        for path in report.plan.edited_paths() {
            let Some(original) = texts.get(path) else { continue };
            let updated = report.plan.apply_file(path, original);
            if let Err(e) = std::fs::write(path, &updated) {
                errln!("steins: cannot write {path}: {e}");
                return ExitCode::FAILURE;
            }
            written += 1;
        }
        for nf in &report.plan.new_files {
            if let Err(e) = std::fs::write(&nf.path, &nf.contents) {
                errln!("steins: cannot create {}: {e}", nf.path);
                return ExitCode::FAILURE;
            }
            written += 1;
        }
        errln!("steins: applied {written} file edit(s)");
    }

    ExitCode::SUCCESS
}

/// `steins.toml` — the `[transform.vouch]` (ADR-0046 §2) and
/// `[transform.partitions]` (ADR-0047 §7) sections are read this slice. Unknown
/// keys are ignored so the file can carry future config.
#[derive(serde::Deserialize, Default)]
struct SteinsConfig {
    transform: Option<TransformConfig>,
    runtime: Option<RuntimeConfig>,
    /// The `[check]` section (ADR-0050 §5): the repo's default profile selection.
    check: Option<CheckConfig>,
    /// The `[profile.<name>]` table (ADR-0050 §5): user-defined profiles.
    profile: Option<std::collections::BTreeMap<String, ProfileEntryConfig>>,
    /// The `[plugins]` section (ADR-0039/0068): the explicit plugin listing.
    plugins: Option<PluginsConfig>,
}

/// The `[plugins]` section (ADR-0039 discovery, ADR-0068 §2 ownership).
///
/// `allow = ["acme/steins-plugin"]` **replaces** `installed.json` discovery with
/// exactly these Composer package names — the explicit listing wins, which is why
/// `allow = []` is a meaningful value (load nothing) rather than a missing one.
/// Listing a plugin also vouches for its identity, lifting the vendor-root rule on
/// the labels it may register.
#[derive(serde::Deserialize, Default)]
#[serde(deny_unknown_fields)]
struct PluginsConfig {
    #[serde(default)]
    allow: Vec<String>,
}

/// The `[check]` section (ADR-0050 §5): repo defaults for `steins check`. Today it
/// carries the default profile name; the `--profile` flag beats it (§5).
#[derive(serde::Deserialize, Default)]
struct CheckConfig {
    profile: Option<String>,
}

/// A `[profile.<name>]` entry (ADR-0050 §5): `extends` a base and refines it with
/// ADR-0022 prefix id-arrays. Facet selection is not accepted here in v1 (the
/// deferred-with-design lenient path, §4/§11): a facet-shaped token in any array is
/// an unknown id pattern and errors clearly.
#[derive(serde::Deserialize, Default)]
struct ProfileEntryConfig {
    extends: Option<String>,
    #[serde(default)]
    enable: Vec<String>,
    #[serde(default)]
    disable: Vec<String>,
    #[serde(default)]
    warn: Vec<String>,
}

/// The `[runtime]` section (ADR-0037 §2): boot-truth pseudo-constants the checker
/// cannot observe from source. `deny_unknown_fields` makes a misspelled key a hard
/// parse error — a security-relevant knob (a silently-ignored `warning-handler` typo
/// would leave the safe default in force while the user believed otherwise). This is
/// also where the abolished `zend-assertions` key now lands: the 2026-07-25 owner
/// ruling reads `assert($expr)` as a throw-guard (Verified unconditionally), so a
/// `steins.toml` still carrying `zend-assertions` is an unknown-key config error
/// (exit 2) — the correct hard-config-error outcome. Reserved keys for future runtime
/// pseudo-constants (ADR-0049's `include-path`, `sapi`) join here as they land.
#[derive(serde::Deserialize, Default)]
#[serde(deny_unknown_fields)]
struct RuntimeConfig {
    /// `warning-handler = "abort" | "null"` (ADR-0049 §7 amendment): what a proven
    /// `E_WARNING` *does* at runtime. Default (or absence) is `"abort"` — the
    /// owner-confirmed realistic-app assumption that a handler converts the warning to
    /// an exception / halts, so proven warning-grade offset findings emit. `"null"`
    /// declares the app tolerates the warning: those findings leave the proof surface
    /// and stay silent.
    #[serde(rename = "warning-handler", default)]
    warning_handler: Option<String>,
}

#[derive(serde::Deserialize, Default)]
struct TransformConfig {
    vouch: Option<VouchConfig>,
    partitions: Option<PartitionsConfig>,
}

#[derive(serde::Deserialize, Default)]
struct VouchConfig {
    /// User-vouched dynamic-code sites as `file:line` entries.
    #[serde(default)]
    sites: Vec<String>,
}

/// The `[transform.partitions]` section (ADR-0047 §7): declared observer globs and
/// the `[transform.partitions.sets]` name→glob-list table. Region assignment is a
/// pure function of these plus the file path ([`PartitionMap`]).
#[derive(serde::Deserialize, Default)]
struct PartitionsConfig {
    /// Observer path-sets (tests, dev-scripts; ADR-0047 §1).
    #[serde(default)]
    observers: Vec<String>,
    /// Partition name → glob list. A `BTreeMap` gives deterministic iteration;
    /// partitions are disjoint (validated), so order never affects assignment.
    #[serde(default)]
    sets: std::collections::BTreeMap<String, Vec<String>>,
}

/// Load the vouching valve from `steins.toml` (ADR-0046 §2). Reads `--config` when
/// given, else `./steins.toml` if it exists (a missing default file is silently
/// no vouches). Returns the [`VouchSet`] plus human warnings for a missing
/// explicit `--config`, a parse error, or a malformed `file:line` entry.
fn load_vouches(config_path: Option<&str>) -> (VouchSet, Vec<String>) {
    let mut warnings = Vec::new();
    let (path, explicit) = match config_path {
        Some(p) => (PathBuf::from(p), true),
        None => (PathBuf::from("steins.toml"), false),
    };
    let text = match std::fs::read_to_string(&path) {
        Ok(t) => t,
        Err(_) => {
            if explicit {
                warnings.push(format!("--config {}: cannot read; proceeding with no vouches", path.display()));
            }
            return (VouchSet::empty(), warnings);
        }
    };
    let config: SteinsConfig = match toml::from_str(&text) {
        Ok(c) => c,
        Err(e) => {
            warnings.push(format!("{}: parse error ({e}); proceeding with no vouches", path.display()));
            return (VouchSet::empty(), warnings);
        }
    };
    let sites = config.transform.and_then(|t| t.vouch).map(|v| v.sites).unwrap_or_default();
    let mut entries: Vec<(String, u32)> = Vec::new();
    for raw in sites {
        // `file:line` — split on the LAST colon so Windows drive letters survive.
        match raw.rsplit_once(':').and_then(|(f, l)| {
            let line = l.trim().parse::<u32>().ok()?;
            (!f.trim().is_empty()).then(|| (f.trim().to_owned(), line))
        }) {
            Some(entry) => entries.push(entry),
            None => warnings.push(format!(
                "steins.toml [transform.vouch]: malformed site `{raw}` (want `file:line`); skipped"
            )),
        }
    }
    (VouchSet::from_entries(entries), warnings)
}

/// The `[plugins] allow` list from an already-parsed config: `Some(names)` when
/// the section is present (an empty list is a deliberate "load nothing"), `None`
/// when it is absent, which leaves `installed.json` discovery in charge.
fn allow_list(plugins: Option<PluginsConfig>) -> Option<Vec<String>> {
    plugins.map(|p| p.allow)
}

/// [`allow_list`] for the surfaces that do not already hold a parsed config
/// (`annotate`, `effect-diff`, `transform`). Leniently: a `steins.toml` that does
/// not parse leaves discovery in charge here, because `check`/`doctor` are the
/// surfaces that turn a malformed config into exit 2, and they run first.
fn allow_list_from_disk() -> Option<Vec<String>> {
    allow_list(read_steins_config().ok().flatten().and_then(|c| c.plugins))
}

/// Load the plugin channel (ADR-0068) for `layout`, reporting every load-time
/// refusal on stderr.
///
/// A rejected label, an unsupported `steins-plugin-api`, a package with no
/// manifest: each is one line, naming the plugin. Never a diagnostic — the zero-FP
/// banner covers what Steins proves about the user's code, and a third party's
/// packaging mistake is not that. Silence names itself instead.
fn load_plugins(layout: &ProjectLayout, allow: Option<&[String]>) -> PluginFacts {
    let facts = PluginFacts::discover(layout, allow);
    for notice in facts.notices() {
        errln!("steins: {notice}");
    }
    facts
}

/// Read and parse `./steins.toml` once for `check`/`doctor` (ADR-0050 §7 /
/// ADR-0052 §5 N2). Returns:
///
/// * `Ok(None)` — no `steins.toml` (the built-in defaults govern);
/// * `Ok(Some(config))` — the parsed config;
/// * `Err(message)` — the file exists but does not parse. A malformed file,
///   INCLUDING an unknown key in `[runtime]` (`RuntimeConfig` uses
///   `deny_unknown_fields`), is a hard config error the caller maps to exit 2 —
///   never a warn-and-proceed. This is the one place `steins.toml` leniency is the
///   wrong default: a silently-ignored `warning-hadler` typo would leave the safe
///   runtime default in force while the user believed they had overridden it. (The
///   abolished `zend-assertions` key reaches the same exit-2 path, as intended.)
///
/// Transform's `--config` path keeps its own lenient loaders (`load_vouches` /
/// `load_partitions`, ADR-0046 §2): a vouch typo must not stop a transform run.
fn read_steins_config() -> Result<Option<SteinsConfig>, String> {
    let path = PathBuf::from("steins.toml");
    let text = match std::fs::read_to_string(&path) {
        Ok(t) => t,
        Err(_) => return Ok(None),
    };
    toml::from_str::<SteinsConfig>(&text)
        .map(Some)
        .map_err(|e| format!("{}: parse error ({e})", path.display()))
}

/// Derive the `[runtime]` pseudo-constants (ADR-0049 §7) from the already-parsed
/// config. Returns `(warning_handler_abort)` plus human warnings for an unrecognized
/// *value* on a known key (a parse error / unknown key already exited 2 in
/// [`read_steins_config`]). Absence is the safe default — `warning-handler = "abort"`.
fn runtime_from_config(runtime: Option<RuntimeConfig>) -> (bool, Vec<String>) {
    let mut warnings = Vec::new();
    let runtime = runtime.unwrap_or_default();
    // Default "abort": a proven E_WARNING is a proven runtime break (ADR-0049 §7).
    let warning_handler_abort = match runtime.warning_handler.as_deref() {
        None | Some("abort") => true,
        Some("null") => false,
        Some(other) => {
            warnings.push(format!(
                "steins.toml [runtime] warning-handler: unknown value `{other}` (want \"abort\"|\"null\"); using abort"
            ));
            true
        }
    };
    (warning_handler_abort, warnings)
}

/// Derive the profile selection and user-profile table from the already-parsed
/// config (ADR-0050 §5). Returns the `[check] profile` selection (the repo default;
/// the `--profile` flag beats it) and the resolved [`profile::ProfileConfigs`] table.
/// The parse itself already happened in [`read_steins_config`] (a parse error exited
/// 2 there), so this is a pure decomposition.
fn profiles_from_config(
    check: Option<CheckConfig>,
    profile: Option<std::collections::BTreeMap<String, ProfileEntryConfig>>,
) -> (Option<String>, profile::ProfileConfigs) {
    let selected = check.and_then(|c| c.profile);
    let map = profile
        .unwrap_or_default()
        .into_iter()
        .map(|(name, e)| {
            (
                name,
                profile::UserProfile {
                    extends: e.extends,
                    enable: e.enable,
                    disable: e.disable,
                    warn: e.warn,
                },
            )
        })
        .collect();
    (selected, profile::ProfileConfigs(map))
}

/// Load the region map from `steins.toml [transform.partitions]` (ADR-0047 §7).
/// Reads `--config` when given, else `./steins.toml` if present.
///
/// Returns `Ok(None)` — the single-region identity — when the file is missing,
/// unparseable (the vouch loader already surfaces the parse warning), or carries
/// no `[transform.partitions]` section; a run with no partition config is then
/// byte-identical to today's behavior. Returns `Err` only for a genuine config
/// error: overlapping partition path-sets (which have no defined assignment).
fn load_partitions(config_path: Option<&str>) -> Result<Option<PartitionMap>, String> {
    let path = match config_path {
        Some(p) => PathBuf::from(p),
        None => PathBuf::from("steins.toml"),
    };
    let Ok(text) = std::fs::read_to_string(&path) else {
        return Ok(None);
    };
    // A parse error is already reported by `load_vouches`; proceed as identity here
    // rather than double-warning.
    let Ok(config) = toml::from_str::<SteinsConfig>(&text) else {
        return Ok(None);
    };
    let Some(partitions) = config.transform.and_then(|t| t.partitions) else {
        return Ok(None);
    };
    // An empty section (no sets, no observers) is still the identity.
    if partitions.sets.is_empty() && partitions.observers.is_empty() {
        return Ok(None);
    }
    PartitionMap::build(partitions.sets, partitions.observers)
        .map(Some)
        .map_err(|e| format!("steins.toml [transform.partitions]: {e}"))
}

/// The outcome of the dual-verification post-check: whether the edited project is
/// clean, plus any diagnostics whose per-id count *increased* after the edits.
struct PostCheck {
    ok: bool,
    new_diagnostics: Vec<Diagnostic>,
}

/// Re-analyze the project with the plan's edits applied and report any diagnostic
/// id whose count increased (ADR-0034 point 3a). Comparison is by per-id count so
/// it is robust to the line-number shifts a tag deletion causes; vendor findings
/// are filtered from both sides, matching `check`'s default (ADR-0015).
fn post_check(
    db: &SteinsDatabase,
    project: Project,
    report: &TransformReport,
    texts: &HashMap<String, String>,
) -> PostCheck {
    if report.plan.is_empty() {
        return PostCheck { ok: true, new_diagnostics: Vec::new() };
    }
    let before = filtered_diagnostics(project.layout(db), check_project(db, project, &mut NoFold));

    // Build the edited project in a fresh database (avoids salsa mutation subtlety
    // and keeps the pre-edit query results intact for `before`).
    let edb = SteinsDatabase::default();
    let mut einputs: Vec<SourceFile> = Vec::new();
    for (path, original) in texts {
        let updated = report.plan.apply_file(path, original);
        einputs.push(SourceFile::new(&edb, path.clone(), updated));
    }
    // The edited project is the same project: it must classify vendor the same way
    // or the before/after comparison is measuring the layout, not the edit.
    let eproject =
        Project::new(&edb, einputs, project.layout(db).clone(), project.plugins(db).clone());
    let after = filtered_diagnostics(eproject.layout(&edb), check_project(&edb, eproject, &mut NoFold));

    let mut before_counts: HashMap<&str, usize> = HashMap::new();
    for d in &before {
        *before_counts.entry(d.id).or_default() += 1;
    }
    let mut after_counts: HashMap<&str, usize> = HashMap::new();
    for d in &after {
        *after_counts.entry(d.id).or_default() += 1;
    }
    let regressed_ids: Vec<&str> = after_counts
        .iter()
        .filter(|(id, n)| **n > before_counts.get(**id).copied().unwrap_or(0))
        .map(|(id, _)| *id)
        .collect();

    let new_diagnostics: Vec<Diagnostic> =
        after.into_iter().filter(|d| regressed_ids.contains(&d.id)).collect();
    PostCheck { ok: new_diagnostics.is_empty(), new_diagnostics }
}

fn filtered_diagnostics(layout: &ProjectLayout, mut ds: Vec<Diagnostic>) -> Vec<Diagnostic> {
    ds.retain(|d| !layout.is_vendor(&d.path));
    ds
}

/// Render the transform dry-run/apply report as text: a unified diff per edited
/// file, then the refusals, the completeness-oracle summary, and the post-check
/// verdict.
fn print_transform_text(
    report: &TransformReport,
    postcheck: &PostCheck,
    texts: &HashMap<String, String>,
    action: &str,
) {
    for path in report.plan.edited_paths() {
        if let Some(original) = texts.get(path) {
            let updated = report.plan.apply_file(path, original);
            out!("{}", unified_diff(path, original, &updated, 3));
        }
    }

    // Project-global dynamic-code obstacles (ADR-0046 §2): recorded once, with the
    // site list capped in text output (the JSON carries every site).
    const OBSTACLE_SITE_CAP: usize = 5;
    if !report.obstacles.is_empty() {
        outln!("\nDynamic-code obstacles ({}):", report.obstacles.len());
        for ob in &report.obstacles {
            outln!("  [{}] {} — {} site(s):", ob.reason, ob.detail, ob.sites.len());
            for s in ob.sites.iter().take(OBSTACLE_SITE_CAP) {
                outln!("    {}:{}:{}: {}", s.path, s.line, s.column, s.label);
            }
            if ob.sites.len() > OBSTACLE_SITE_CAP {
                outln!("    … and {} more (see --format json)", ob.sites.len() - OBSTACLE_SITE_CAP);
            }
        }
    }

    if !report.refusals.is_empty() {
        outln!("\nRefusals ({}):", report.refusals.len());
        for r in &report.refusals {
            outln!(
                "  {}:{}:{}: {} [{}] — {}",
                r.site.path, r.site.line, r.site.column, r.site.label, r.reason, r.detail
            );
        }
    }

    let o = &report.oracle;
    outln!("\n{} enumerated: {} {action}, {} refused", o.enumerated, o.transformed, o.refused);

    // The vouching downgrade (ADR-0046 §2 / ADR-0037): a run that vouched sites
    // does not silently pass — its completeness claim is conditional on those
    // user assertions, and the report says so prominently.
    if !report.vouched_exemptions.is_empty() {
        outln!(
            "\nDOWNGRADE: completeness claim is conditional on {} user-vouched dynamic-code exemption(s):",
            report.vouched_exemptions.len()
        );
        for s in &report.vouched_exemptions {
            outln!("    vouched {}:{}:{}: {}", s.path, s.line, s.column, s.label);
        }
    }

    if !postcheck.ok {
        outln!("\nPost-check FAILED — {} new diagnostic(s):", postcheck.new_diagnostics.len());
        for d in &postcheck.new_diagnostics {
            outln!("  {}:{}:{}: [{}] {}", d.path, d.line, d.column, d.id, d.message);
        }
    } else if !report.plan.is_empty() {
        outln!("Post-check OK — no new diagnostics.");
    }
}

/// Render the transform report as JSON: the serializable [`TransformReport`]
/// (plan + refusals + oracle) plus the post-check verdict and whether the edits
/// were written.
fn print_transform_json(report: &TransformReport, postcheck: &PostCheck, applied: bool) {
    let new_ds: Vec<serde_json::Value> = postcheck
        .new_diagnostics
        .iter()
        .map(|d| {
            serde_json::json!({
                "id": d.id, "path": d.path, "line": d.line,
                "column": d.column, "message": d.message,
            })
        })
        .collect();
    // The vouching downgrade (ADR-0046 §2): the `report` already serializes the
    // `obstacles` and `vouched_exemptions` arrays; surface the claim downgrade as a
    // prominent top-level note whenever any site was vouched.
    let downgrade_note = (!report.vouched_exemptions.is_empty()).then(|| {
        format!(
            "completeness claim is conditional on {} user-vouched dynamic-code exemption(s)",
            report.vouched_exemptions.len()
        )
    });
    let doc = serde_json::json!({
        "report": report,
        "postcheck": { "ok": postcheck.ok, "new_diagnostics": new_ds },
        "applied": applied,
        "downgrade_note": downgrade_note,
    });
    match serde_json::to_string_pretty(&doc) {
        Ok(s) => outln!("{s}"),
        Err(e) => errln!("steins: failed to serialize json: {e}"),
    }
}

/// `steins annotate [--no-php] [--format text|json] <file.php>` — reprint one
/// file with a right-margin column of proven inferred facts (ADR-0020), or (with
/// `--format json`) emit the same effect summaries as a machine-readable
/// document (issue #65). Never modifies the file; output goes to stdout. Exits
/// 2 on a usage error (directory, missing/extra args).
fn run_annotate(args: &[String]) -> ExitCode {
    let mut no_php = false;
    let mut format = Format::Text;
    let mut project_dir: Option<String> = None;
    let mut paths: Vec<String> = Vec::new();
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--no-php" => {
                no_php = true;
                i += 1;
            }
            "--project" => {
                let Some(dir) = args.get(i + 1) else {
                    errln!("steins: --project requires a directory argument");
                    return ExitCode::from(2);
                };
                project_dir = Some(dir.clone());
                i += 2;
            }
            "--format" => {
                let Some(value) = args.get(i + 1) else {
                    errln!("steins: --format requires an argument (text|json)");
                    return ExitCode::from(2);
                };
                match value.as_str() {
                    "text" => format = Format::Text,
                    "json" => format = Format::Json,
                    other => {
                        errln!("steins: unknown format `{other}` (text|json)");
                        return ExitCode::from(2);
                    }
                }
                i += 2;
            }
            other if other.starts_with('-') => {
                errln!("steins: unknown flag `{other}` for annotate");
                return ExitCode::from(2);
            }
            other => {
                paths.push(other.to_owned());
                i += 1;
            }
        }
    }

    let [path] = paths.as_slice() else {
        errln!(
            "steins: annotate takes exactly one file (usage: steins annotate [--no-php] [--format text|json] [--project <dir>] <file.php>)"
        );
        return ExitCode::from(2);
    };
    let path = Path::new(path);
    if path.is_dir() {
        errln!("steins: annotate expects a single file, not a directory: {}", path.display());
        return ExitCode::from(2);
    }
    let text = match std::fs::read(path) {
        Ok(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
        Err(e) => {
            errln!("steins: cannot read {}: {e}", path.display());
            return ExitCode::from(2);
        }
    };

    // Same coverage posture as `check` (ADR-0004).
    if no_php {
        errln!("{SOUND_SUBSET_NOTICE}");
    }
    let db = SteinsDatabase::default();
    let mut folder = if no_php { SidecarFolder::new(true) } else { SidecarFolder::enabled() };

    // The project context for cross-file facts (ADR-0015): the `--project`
    // directory, else the file's own directory. Every `.php` file under it is
    // parsed into one project so `annotate` sees cross-file resolution.
    let root = project_dir
        .map(PathBuf::from)
        .unwrap_or_else(|| path.parent().map(Path::to_path_buf).unwrap_or_else(|| PathBuf::from(".")));

    let canon_target = path.canonicalize().unwrap_or_else(|_| path.to_path_buf());
    let mut project_files = Vec::new();
    collect_php_files(&root, &mut project_files);
    project_files.sort();
    project_files.dedup();

    let mut inputs: Vec<SourceFile> = Vec::new();
    let mut target: Option<SourceFile> = None;
    for fp in &project_files {
        let content = if fp.canonicalize().map(|c| c == canon_target).unwrap_or(false) {
            text.clone()
        } else {
            match std::fs::read(fp) {
                Ok(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
                Err(_) => continue,
            }
        };
        let input = SourceFile::new(&db, fp.to_string_lossy().into_owned(), content);
        if fp.canonicalize().map(|c| c == canon_target).unwrap_or(false) {
            target = Some(input);
        }
        inputs.push(input);
    }

    // If the target file was not found under the root (e.g. an explicit path
    // outside the project dir), fall back to a one-file project. `--format
    // json` (issue #65) reads the same [`EffectSummary`]s the text margin's
    // effect facts are rendered from, so the two surfaces cannot disagree.
    match format {
        Format::Text => {
            let facts = match target {
                Some(target_file) => {
                    let layout = resolve_layout(&[root.to_string_lossy().into_owned()]);
                    folder.set_php_target(layout.php_target().cloned());
                    let plugins = load_plugins(&layout, allow_list_from_disk().as_deref());
                    let project = Project::new(&db, inputs, layout, plugins);
                    annotate_project(&db, project, target_file, &mut folder)
                }
                None => {
                    let input =
                        SourceFile::new(&db, path.to_string_lossy().into_owned(), text.clone());
                    annotate_file(&db, input, &mut folder)
                }
            };
            out!("{}", render_annotation(&text, &facts));
        }
        Format::Json => {
            let summaries = match target {
                Some(target_file) => {
                    let layout = resolve_layout(&[root.to_string_lossy().into_owned()]);
                    let plugins = load_plugins(&layout, allow_list_from_disk().as_deref());
                    let project = Project::new(&db, inputs, layout, plugins);
                    effect_summaries_project(&db, project, target_file)
                }
                None => {
                    let input =
                        SourceFile::new(&db, path.to_string_lossy().into_owned(), text.clone());
                    effect_summaries_file(&db, input)
                }
            };
            print_annotate_json(&summaries);
        }
    }
    ExitCode::SUCCESS
}

/// `annotate --format json`'s document (issue #65): a top-level `functions`
/// array, one entry per analyzed function/method, each carrying the same
/// dimensions the text margin's `effects: {…}` / `≤` / `…?` spells — the sorted
/// proven labels, the sorted **declared** bounds (ADR-0067), and the
/// exhaustiveness bit — as distinct fields rather than one flattened string.
/// Only proven labels go in `effects`; the two lanes are never merged here, and
/// `declared` arrives already normalized against `effects` (a bound the proven
/// lane subsumes is dropped, exactly as the margin drops it).
fn print_annotate_json(summaries: &[EffectSummary]) {
    let functions: Vec<serde_json::Value> = summaries
        .iter()
        .map(|s| {
            serde_json::json!({
                "name": s.symbol,
                "line": s.line,
                "effects": s.labels,
                "declared": s.declared,
                "exhaustive": s.exhaustive,
            })
        })
        .collect();
    let doc = serde_json::json!({ "functions": functions });
    match serde_json::to_string_pretty(&doc) {
        Ok(s) => outln!("{s}"),
        Err(e) => errln!("steins: failed to serialize json: {e}"),
    }
}

/// `steins effect-diff [--baseline <path>] [--set-baseline] [--format text|json]
/// <paths...>` (issue #69) — capture the project's per-function effect summaries,
/// or report how today's differ from a captured past.
///
/// The review story for an effect-neutral refactor: capture before, refactor,
/// run again, and read one line per changed function. It touches neither `check`
/// nor the diagnostic baseline — its own sidecar file, its own format, no
/// suppression, and no verdict. The diff is informational, so a run that finds
/// changes still exits 0; only a usage or file error exits 2. Gating a build on
/// an effect delta is a policy decision (ADR-0023's territory), not this
/// surface's.
fn run_effect_diff(args: &[String]) -> ExitCode {
    let mut format = Format::Text;
    let mut set_baseline = false;
    let mut baseline_path: Option<String> = None;
    let mut paths: Vec<String> = Vec::new();
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--set-baseline" => {
                set_baseline = true;
                i += 1;
            }
            "--baseline" => {
                let Some(value) = args.get(i + 1) else {
                    errln!("steins: --baseline requires a path argument");
                    return ExitCode::from(2);
                };
                baseline_path = Some(value.clone());
                i += 2;
            }
            "--format" => {
                let Some(value) = args.get(i + 1) else {
                    errln!("steins: --format requires an argument (text|json)");
                    return ExitCode::from(2);
                };
                match value.as_str() {
                    "text" => format = Format::Text,
                    "json" => format = Format::Json,
                    other => {
                        errln!("steins: unknown format `{other}` (text|json)");
                        return ExitCode::from(2);
                    }
                }
                i += 2;
            }
            other if other.starts_with('-') => {
                errln!("steins: unknown flag `{other}` for effect-diff");
                return ExitCode::from(2);
            }
            other => {
                paths.push(other.to_owned());
                i += 1;
            }
        }
    }

    if paths.is_empty() {
        errln!("steins: no paths given");
        return ExitCode::from(2);
    }
    if let Err(code) = reject_missing_paths(&paths) {
        return code;
    }

    let mut files = Vec::new();
    for p in &paths {
        collect_php_files(Path::new(p), &mut files);
    }
    files.sort();
    files.dedup();

    // No sidecar, no folder: effect summaries are a pure static fixpoint, so this
    // command never needs `php` and takes no `--no-php`.
    let db = SteinsDatabase::default();
    let mut inputs: Vec<SourceFile> = Vec::new();
    for file_path in &files {
        let text = match std::fs::read(file_path) {
            Ok(bytes) => String::from_utf8_lossy(&bytes).into_owned(),
            Err(e) => {
                errln!("steins: cannot read {}: {e}", file_path.display());
                continue;
            }
        };
        inputs.push(SourceFile::new(&db, file_path.to_string_lossy().into_owned(), text));
    }
    let layout = resolve_layout(&paths);
    let plugins = load_plugins(&layout, allow_list_from_disk().as_deref());
    let project = Project::new(&db, inputs.clone(), layout.clone(), plugins);

    // The sidecar file, resolved exactly like the diagnostic baseline's: the
    // `--baseline` path, else the default name in the working directory. Entry
    // paths are relative to its directory (ADR-0022's relativization, reused).
    let file = PathBuf::from(baseline_path.as_deref().unwrap_or(effect_baseline::DEFAULT_FILE));
    let dir = baseline::base_dir(&file);
    let current = capture_effect_entries(&db, project, &inputs, &layout, &dir);

    if set_baseline {
        let n = current.len();
        return match std::fs::write(&file, effect_baseline::render(current)) {
            Ok(()) => {
                errln!("steins: wrote {n} effect summaries to {}", file.display());
                ExitCode::SUCCESS
            }
            Err(e) => {
                errln!("steins: cannot write effect baseline {}: {e}", file.display());
                ExitCode::from(2)
            }
        };
    }

    let text = match std::fs::read_to_string(&file) {
        Ok(t) => t,
        Err(e) => {
            errln!(
                "steins: cannot read effect baseline {}: {e} (run --set-baseline to capture one)",
                file.display()
            );
            return ExitCode::from(2);
        }
    };
    let doc = match effect_baseline::parse(&text) {
        Ok(d) => d,
        Err(e) => {
            errln!("steins: {}: {e}", file.display());
            return ExitCode::from(2);
        }
    };

    let report = effect_baseline::diff(&doc.functions, &current);
    match format {
        Format::Text => {
            for event in &report.events {
                outln!("{}", event.line());
            }
            if let Some(footer) = effect_baseline::footer(&report) {
                outln!("{footer}");
            }
        }
        Format::Json => print_effect_diff_json(&report),
    }
    ExitCode::SUCCESS
}

/// The current run's effect summaries as baseline entries, one per analyzed
/// non-vendor function/method.
///
/// Vendor files are excluded exactly as `check` excludes vendor findings
/// (ADR-0015): they are still indexed and still contribute to every summary
/// through the call graph, but someone else's function is not this project's
/// effect surface to review.
fn capture_effect_entries(
    db: &SteinsDatabase,
    project: Project,
    inputs: &[SourceFile],
    layout: &ProjectLayout,
    dir: &Path,
) -> Vec<effect_baseline::Entry> {
    let mut entries = Vec::new();
    for &input in inputs {
        let path = input.path(db).to_owned();
        if layout.is_vendor(&path) {
            continue;
        }
        let rel = baseline::relativize(dir, &path);
        // One whole-project effect fixpoint per target file — the same cost
        // `annotate` pays per invocation, paid once per file here. Acceptable for a
        // capture-and-compare surface; if it ever bites, the fixpoint (not this
        // loop) is what should learn to answer for every file at once.
        for s in effect_summaries_project(db, project, input) {
            entries.push(effect_baseline::Entry {
                file: rel.clone(),
                symbol: s.qualified,
                proven: s.labels,
                declared: s.declared,
                exhaustive: s.exhaustive,
            });
        }
    }
    entries
}

/// `effect-diff --format json`: the itemized `events` array plus the footer
/// counts, so a CI job can read the same delta the text lines spell.
fn print_effect_diff_json(report: &effect_baseline::Diff) {
    let events: Vec<serde_json::Value> = report
        .events
        .iter()
        .map(|e| {
            serde_json::json!({
                "file": e.file,
                "symbol": e.symbol,
                "category": e.category.as_str(),
                "label": e.label,
            })
        })
        .collect();
    let doc = serde_json::json!({
        "events": events,
        "compared": report.compared,
        "not_in_baseline": report.not_in_baseline,
        "no_longer_present": report.no_longer_present,
    });
    match serde_json::to_string_pretty(&doc) {
        Ok(s) => outln!("{s}"),
        Err(e) => errln!("steins: failed to serialize json: {e}"),
    }
}

/// Render the annotated file: each source line reprinted verbatim, and lines
/// with a proven fact padded (to the longest line, capped at column 88) and
/// given a `//=>` margin. Multiple facts on one line join with `; `.
fn render_annotation(text: &str, facts: &[LineFact]) -> String {
    /// The column source lines are padded to before the margin (cap: longer
    /// lines simply get a single separating space).
    const CAP: usize = 88;
    const PREFIX: &str = "//=> ";

    let lines: Vec<&str> = text.lines().collect();

    // Group fact bodies by line, de-duplicating identical bodies, order-stable.
    let mut by_line: std::collections::BTreeMap<u32, Vec<String>> = std::collections::BTreeMap::new();
    for f in facts {
        let bodies = by_line.entry(f.line).or_default();
        let body = f.body();
        if !bodies.contains(&body) {
            bodies.push(body);
        }
    }

    let target = lines.iter().map(|l| l.chars().count()).max().unwrap_or(0).min(CAP);

    let mut out = String::new();
    for (i, line) in lines.iter().enumerate() {
        let line_no = i as u32 + 1;
        out.push_str(line);
        if let Some(bodies) = by_line.get(&line_no) {
            let width = line.chars().count();
            // Pad up to `target`, then always exactly one separating space — so
            // margins align at column `target + 1`, and an over-long line (width
            // >= target) simply gets that single space.
            let pad = target.saturating_sub(width) + 1;
            for _ in 0..pad {
                out.push(' ');
            }
            out.push_str(PREFIX);
            out.push_str(&bodies.join("; "));
        }
        out.push('\n');
    }
    out
}

#[allow(clippy::too_many_arguments)]
fn print_text(
    findings: &[Diagnostic],
    surface: &profile::Surface,
    vendor_suppressed: usize,
    suppressed: usize,
    baselined: usize,
    stale: usize,
    surface_notice: Option<&str>,
) {
    for d in findings {
        // The level distinction (ADR-0050 §7): fail-level prints `error[…]`,
        // warn-level (a profile `warn = [...]` demotion) prints `warning[…]`.
        let kind = match surface.level(d.id) {
            profile::Level::Fail => "error",
            profile::Level::Warn => "warning",
        };
        outln!("{}:{}:{}: {kind}[{}]: {}", d.path, d.line, d.column, d.id, d.message);
    }
    // Suppression accounting (ADR-0022/0023/0015), each line printed only when
    // nonzero. Vendor is the first channel (ADR-0015), so it prints first.
    if vendor_suppressed > 0 {
        outln!("{vendor_suppressed} findings in vendor suppressed (--vendor-diagnostics to show)");
    }
    if suppressed > 0 {
        outln!("{suppressed} diagnostics suppressed by inline ignores");
    }
    if baselined > 0 {
        outln!("{baselined} findings in baseline");
    }
    if stale > 0 {
        outln!("{stale} baseline entries no longer match (stale — rerun --set-baseline)");
    }
    // The drowns-loudly notice (ADR-0050 §8), printed after the accounting.
    if let Some(notice) = surface_notice {
        outln!("{notice}");
    }
}

fn print_json(
    findings: &[Diagnostic],
    surface: &profile::Surface,
    vendor_suppressed: usize,
    suppressed: usize,
    baselined: usize,
) {
    let array: Vec<serde_json::Value> = findings
        .iter()
        .map(|d| {
            let mut obj = serde_json::json!({
                "id": d.id,
                // ADR-0050 §2: the diagnostic layer, additive. Every emitted id is
                // registered (totality test), so this is always present.
                "layer": steins_infer::layer(d.id).map(steins_infer::Layer::as_str),
                // ADR-0050 §7: the exit level (`fail|warn`), additive.
                "level": surface.level(d.id).as_str(),
                "path": d.path,
                "line": d.line,
                "column": d.column,
                "message": d.message,
            });
            // ADR-0050 §4: the registry-declared facet, additive — present as its own
            // key (`"origin": "direct"|"propagated"`) only on ids that declare one.
            if let Some(facet) = d.facet {
                obj[facet.key()] = serde_json::Value::String(facet.value().to_owned());
            }
            obj
        })
        .collect();
    let doc = serde_json::json!({
        "findings": array,
        "profile": surface.name,
        "vendor_suppressed": vendor_suppressed,
        "suppressed": suppressed,
        "baselined": baselined,
    });
    match serde_json::to_string_pretty(&doc) {
        Ok(s) => outln!("{s}"),
        Err(e) => errln!("steins: failed to serialize json: {e}"),
    }
}

/// Reject explicitly-passed paths that name nothing (ADR-0050 §7 amendment).
///
/// A nonexistent path argument is argv, not analysis: it fell through
/// `collect_php_files` silently, so `steins check /typo` reported an empty
/// findings set and exit 0 — a false all-clear indistinguishable from a clean
/// run, which is how a renamed directory keeps a CI job green. Every missing
/// path is named in one message so a multi-path invocation reports all of its
/// typos at once. Callers must run this BEFORE emitting anything, so a
/// `--format json` run produces no document rather than a well-formed empty one.
///
/// Existence is the whole discriminator: a path that exists and yields zero
/// `.php` files is a real location with nothing to say, and stays exit 0.
fn reject_missing_paths(paths: &[String]) -> Result<(), ExitCode> {
    let missing: Vec<&String> = paths.iter().filter(|p| !Path::new(p.as_str()).exists()).collect();
    if missing.is_empty() {
        return Ok(());
    }
    for p in &missing {
        errln!("steins: path does not exist: {p}");
    }
    Err(ExitCode::from(2))
}

/// Recursively collect `.php` files under `path` (or `path` itself if it is a
/// `.php` file).
/// Resolve the run's [`ProjectLayout`] from the analyzed paths (ADR-0015): read
/// each governing `composer.json` for its vendor directory and its own autoload
/// roots, so "is this someone else's code" is answered from what the project
/// declares rather than from a directory name. A tree with no manifest — or an
/// unreadable working directory — resolves to [`ProjectLayout::fallback`], which
/// is the directory-name floor.
fn resolve_layout(paths: &[String]) -> ProjectLayout {
    let Ok(cwd) = std::env::current_dir() else { return ProjectLayout::fallback() };
    let roots: Vec<PathBuf> = paths.iter().map(PathBuf::from).collect();
    composer::discover(&roots, &cwd)
}

fn collect_php_files(path: &Path, out: &mut Vec<PathBuf>) {
    if path.is_dir() {
        let Ok(entries) = std::fs::read_dir(path) else { return };
        for entry in entries.flatten() {
            collect_php_files(&entry.path(), out);
        }
    } else if path.extension().is_some_and(|e| e == "php") {
        out.push(path.to_path_buf());
    }
}
