// @generated by `cargo xtask gen-catalog` from
// docs/research/phpsrc-mining/hierarchy.toml — DO NOT EDIT BY HAND.
//
// php-src tag: php-8.5.11 (597eb0b4e32cc8802e112fe13cc92fb5636a1781). Source of
// record is the TOML; run
// `cargo xtask gen-catalog` to regenerate after editing it.
//
// Each row: (lowercased SECOND name, the class's declared name). A stub's
// class-level `@alias` registers a second name for the same class entry, so
// `ReflectionClass::getName()` of either spelling answers the declared name
// and every is-a, catch and type check treats the two as one class (#917).
// The second name is no row of HIERARCHY or DISPLAY_NAMES; those answer
// through this table.
//
// Sorted by key for binary search.

pub(crate) static CLASS_ALIASES: &[(&str, &str)] = &[
    ("dom\\domexception", "DOMException"),
];
