// @generated by `cargo xtask gen-catalog` from
// docs/research/phpstan-mining/migrated_resource_classes.toml — DO NOT EDIT BY HAND.
//
// The MIGRATED-CLASS table (ADR-0097 §2.6): every class the pinned engine
// declares as the return of a function PHPStan's functionMap still spells
// `resource` — `CurlHandle` for `curl_init`, `GdImage` for the `imagecreate*`
// family, `LDAP\Result`, `PgSql\Connection`, `finfo`, …. It is the extension
// of "a class PHP migrated a resource into", derived from the one disagreement
// the ADR-0069 countersign records (`mine-function-map --migrated`) rather than
// hand-listed, off the BASE functionMap — the last record of what returned a
// resource before PHP 8 — so it is per class, not per row.
//
// WHERE IT SPEAKS: the contract relation, an OBJECT value against `@param
// resource`. A class here stays `Maybe` — the docblock is the suspect, a decade
// of `@param resource $ch` inherited across PHP 8's migration (ADR-0056 §8.5) —
// and an object of any other class is `No`: a genuine docblock violation, the
// verdict every other analyzer on the conformance page reaches. It retires
// itself (ADR-0097 §2.8): a class leaves when the resource era leaves the base
// map, i.e. when PHPStan drops the PHP that returned it.
//
// LINEAGE — see the root NOTICE file for both MIT permission notices:
//   Steins <- phpstan-src `resources/functionMap.php`
//              (MIT, Copyright (c) Ondrej Mirtes and contributors)
//          <- Phan `src/Phan/Language/Internal/FunctionSignatureMap.php`
//              (MIT, Copyright (c) 2015 Rasmus Lerdorf,
//                   Copyright (c) 2015 Andrew Morrison)
//
// phpstan-src pin: dcde2be6ca3caae0e0d4bee6bfbc9fd39ea560e7 (declared_returns.toml's, read with `git show`)
// asked of PHP 8.5.10 via the real sidecar.
//
// Counts at the pin:
//     368  base-map functions whose return type spells `resource`
//      92  of those, the engine declares a class for (the `from` lists in the TOML)
//      27  distinct classes (the table below)
//     276  functions contributing no class, of which
//     251    the engine does not have (an unloaded extension)
//      22    still declare no return type (the producers ADR-0056 §8.2 admits)
//       3    declare a type naming no class
//
// Each row: (lowercased class name, the engine's own casing). The lookup is
// case-insensitive with the leading `\` stripped — the normalization
// `ContractTy::Class` applies — and compares the whole FQN, so a project
// `App\CurlHandle` is not `CurlHandle`. Sorted by key for binary search.

pub(crate) static MIGRATED_RESOURCE_CLASSES: &[(&str, &str)] = &[
    ("curlhandle", "CurlHandle"),
    ("curlmultihandle", "CurlMultiHandle"),
    ("curlsharehandle", "CurlShareHandle"),
    ("dba\\connection", "Dba\\Connection"),
    ("deflatecontext", "DeflateContext"),
    ("finfo", "finfo"),
    ("ftp\\connection", "FTP\\Connection"),
    ("gdimage", "GdImage"),
    ("inflatecontext", "InflateContext"),
    ("ldap\\connection", "LDAP\\Connection"),
    ("ldap\\result", "LDAP\\Result"),
    ("ldap\\resultentry", "LDAP\\ResultEntry"),
    ("odbc\\connection", "Odbc\\Connection"),
    ("odbc\\result", "Odbc\\Result"),
    ("opensslasymmetrickey", "OpenSSLAsymmetricKey"),
    ("opensslcertificate", "OpenSSLCertificate"),
    ("opensslcertificatesigningrequest", "OpenSSLCertificateSigningRequest"),
    ("pgsql\\connection", "PgSql\\Connection"),
    ("pgsql\\lob", "PgSql\\Lob"),
    ("pgsql\\result", "PgSql\\Result"),
    ("shmop", "Shmop"),
    ("socket", "Socket"),
    ("sysvmessagequeue", "SysvMessageQueue"),
    ("sysvsemaphore", "SysvSemaphore"),
    ("sysvsharedmemory", "SysvSharedMemory"),
    ("xmlparser", "XMLParser"),
    ("xmlwriter", "XMLWriter"),
];
