// @generated by `cargo xtask gen-catalog` from
// docs/research/phpsrc-mining/resource_returns.toml — DO NOT EDIT BY HAND.
//
// Builtins whose return is a legacy PHP RESOURCE (ADR-0056 §8): the one
// type PHP has no syntax to declare, so the reflected envelope every other
// return fact is anchored to can never carry it. A row is admitted at a
// call site only when all three §7 conditions hold — this table (the stub
// reading at the pin), the analyzing engine declaring NO return type for
// the name (the resource-to-object migration tripwire), and the project
// PHP minor equalling PINNED_PHP.
//
// Each row: (lowercased builtin name, whether the stub's `@return` carries
// a `false` arm, the kind of handle it returns — ADR-0097 §2.1). Sorted by
// key for binary search. Source of record is the TOML, which carries the
// per-row stub path and probe transcript.

use crate::ResourceKind;

pub(crate) static RESOURCE_RETURNS: &[(&str, bool, ResourceKind)] = &[
    ("bzopen", true, ResourceKind::Stream),
    ("fopen", true, ResourceKind::Stream),
    ("fsockopen", true, ResourceKind::Stream),
    ("gzopen", true, ResourceKind::Stream),
    ("opendir", true, ResourceKind::Dir),
    ("pfsockopen", true, ResourceKind::PersistentStream),
    ("pg_socket", true, ResourceKind::Stream),
    ("popen", true, ResourceKind::Stream),
    ("proc_open", true, ResourceKind::Process),
    ("socket_export_stream", true, ResourceKind::Stream),
    ("stream_context_create", false, ResourceKind::StreamContext),
    ("stream_context_get_default", false, ResourceKind::StreamContext),
    ("stream_context_set_default", false, ResourceKind::StreamContext),
    ("stream_filter_append", true, ResourceKind::StreamFilter),
    ("stream_filter_prepend", true, ResourceKind::StreamFilter),
    ("stream_socket_accept", true, ResourceKind::Stream),
    ("stream_socket_client", true, ResourceKind::Stream),
    ("stream_socket_server", true, ResourceKind::Stream),
    ("tmpfile", true, ResourceKind::Stream),
];
