// @generated by `cargo xtask gen-catalog` from
// docs/research/phpsrc-mining/resource_params.toml — DO NOT EDIT BY HAND.
//
// Builtin POSITIONS that demand a legacy PHP RESOURCE (ADR-0097 §2.5), the
// parameter twin of `resource_returns_generated.rs`. PHP has no syntax for a
// `resource` parameter, so the reflected signature every other builtin
// argument is judged against reports NO type here; the stub docblock is the
// only record of the demand. A row is admitted at a call site only when the
// three gate conditions hold — this table (the stub reading at the pin), the
// analyzing engine declaring NO type at the position (the tripwire: the day
// `fwrite` declares `Stream $stream`, the engine speaks and the row is
// disowned), and the project PHP minor equalling PINNED_PHP.
//
// php-src pin 2c7c630e2873cbe4abc70d538c47521611cbd83f; probes at PHP 8.5.10.
//
// Counts at the mining pin:
//     100  rows (one per exactly-`resource` position on a free function)
//      42  positions declined — unions, by-ref, variadic, natively typed, null default
//      15  method positions skipped (ADR-0056 §4's function-keyed bound)
//      16  rows carrying a probe transcript

/// What one builtin position demands of a resource argument (ADR-0097 §2.5).
///
/// `accepts_closed` and `closes` default to `false` and are `true` only where
/// the source of record carries a probe; `kind` is present only where a probe
/// established it. The state-dependent verdicts those bits feed are slice 1's
/// (the heap carries the state); this slice reads only the resource-ness.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ResourceParam {
    /// The parameter's declared name without the `$`, so a finding can name
    /// it the way PHP's own `TypeError` does (`fwrite(): Argument #1 ($stream)`).
    pub name: &'static str,
    /// The position answers on a CLOSED handle (`get_resource_id`); everywhere
    /// else a closed handle is a `TypeError` (`must be an open stream resource`).
    pub accepts_closed: bool,
    /// The call leaves its argument closed when it returns (`fclose`, `pclose`,
    /// `gzclose`, `bzclose`, `proc_close`, `stream_filter_remove`).
    pub closes: bool,
    /// The resource kind the position demands, where a probe established it:
    /// `stream`, `dir`, `process`, `stream-context`, `stream-filter`.
    pub kind: Option<&'static str>,
}

/// Sorted by `(function, index)` for binary search; functions are lowercase.
pub(crate) static RESOURCE_PARAMS: &[(&str, usize, ResourceParam)] = &[
    ("bzclose", 0, ResourceParam { name: "bz", accepts_closed: false, closes: true, kind: None }),
    ("bzerrno", 0, ResourceParam { name: "bz", accepts_closed: false, closes: false, kind: None }),
    ("bzerror", 0, ResourceParam { name: "bz", accepts_closed: false, closes: false, kind: None }),
    ("bzerrstr", 0, ResourceParam { name: "bz", accepts_closed: false, closes: false, kind: None }),
    ("bzflush", 0, ResourceParam { name: "bz", accepts_closed: false, closes: false, kind: None }),
    ("bzread", 0, ResourceParam { name: "bz", accepts_closed: false, closes: false, kind: None }),
    ("bzwrite", 0, ResourceParam { name: "bz", accepts_closed: false, closes: false, kind: None }),
    ("fclose", 0, ResourceParam { name: "stream", accepts_closed: false, closes: true, kind: Some("stream") }),
    ("fdatasync", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("feof", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: Some("stream") }),
    ("fflush", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fgetc", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fgetcsv", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fgets", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("flock", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fpassthru", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fprintf", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fputcsv", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fputs", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fread", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: Some("stream") }),
    ("fscanf", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fseek", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fstat", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fsync", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("ftell", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: Some("stream") }),
    ("ftp_fget", 1, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("ftp_fput", 2, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("ftp_nb_fget", 1, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("ftp_nb_fput", 2, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("ftruncate", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("fwrite", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: Some("stream") }),
    ("get_resource_id", 0, ResourceParam { name: "resource", accepts_closed: true, closes: false, kind: None }),
    ("get_resource_type", 0, ResourceParam { name: "resource", accepts_closed: true, closes: false, kind: None }),
    ("gzclose", 0, ResourceParam { name: "stream", accepts_closed: false, closes: true, kind: None }),
    ("gzeof", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("gzgetc", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("gzgets", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("gzpassthru", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("gzputs", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("gzread", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("gzrewind", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("gzseek", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("gztell", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("gzwrite", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("hash_update_stream", 1, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("libxml_set_streams_context", 0, ResourceParam { name: "context", accepts_closed: false, closes: false, kind: None }),
    ("pclose", 0, ResourceParam { name: "handle", accepts_closed: false, closes: true, kind: None }),
    ("pg_socket_poll", 0, ResourceParam { name: "socket", accepts_closed: false, closes: false, kind: None }),
    ("proc_close", 0, ResourceParam { name: "process", accepts_closed: false, closes: true, kind: Some("process") }),
    ("proc_get_status", 0, ResourceParam { name: "process", accepts_closed: false, closes: false, kind: Some("process") }),
    ("proc_terminate", 0, ResourceParam { name: "process", accepts_closed: false, closes: false, kind: Some("process") }),
    ("rewind", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("sapi_windows_vt100_support", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("set_file_buffer", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("socket_get_status", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("socket_import_stream", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("socket_set_blocking", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("socket_set_timeout", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_bucket_append", 0, ResourceParam { name: "brigade", accepts_closed: false, closes: false, kind: None }),
    ("stream_bucket_make_writeable", 0, ResourceParam { name: "brigade", accepts_closed: false, closes: false, kind: None }),
    ("stream_bucket_new", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_bucket_prepend", 0, ResourceParam { name: "brigade", accepts_closed: false, closes: false, kind: None }),
    ("stream_context_get_options", 0, ResourceParam { name: "stream_or_context", accepts_closed: false, closes: false, kind: None }),
    ("stream_context_get_params", 0, ResourceParam { name: "context", accepts_closed: false, closes: false, kind: None }),
    ("stream_context_set_option", 0, ResourceParam { name: "context", accepts_closed: false, closes: false, kind: None }),
    ("stream_context_set_options", 0, ResourceParam { name: "context", accepts_closed: false, closes: false, kind: None }),
    ("stream_context_set_params", 0, ResourceParam { name: "context", accepts_closed: false, closes: false, kind: None }),
    ("stream_copy_to_stream", 0, ResourceParam { name: "from", accepts_closed: false, closes: false, kind: None }),
    ("stream_copy_to_stream", 1, ResourceParam { name: "to", accepts_closed: false, closes: false, kind: None }),
    ("stream_filter_append", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_filter_prepend", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_filter_remove", 0, ResourceParam { name: "stream_filter", accepts_closed: false, closes: true, kind: None }),
    ("stream_get_contents", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_get_line", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_get_meta_data", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_isatty", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_set_blocking", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_set_chunk_size", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_set_read_buffer", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_set_timeout", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_set_write_buffer", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_socket_accept", 0, ResourceParam { name: "socket", accepts_closed: false, closes: false, kind: None }),
    ("stream_socket_enable_crypto", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_socket_get_crypto_status", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_socket_get_name", 0, ResourceParam { name: "socket", accepts_closed: false, closes: false, kind: None }),
    ("stream_socket_recvfrom", 0, ResourceParam { name: "socket", accepts_closed: false, closes: false, kind: None }),
    ("stream_socket_sendto", 0, ResourceParam { name: "socket", accepts_closed: false, closes: false, kind: None }),
    ("stream_socket_shutdown", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("stream_supports_lock", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("vfprintf", 0, ResourceParam { name: "stream", accepts_closed: false, closes: false, kind: None }),
    ("zip_close", 0, ResourceParam { name: "zip", accepts_closed: false, closes: false, kind: None }),
    ("zip_entry_close", 0, ResourceParam { name: "zip_entry", accepts_closed: false, closes: false, kind: None }),
    ("zip_entry_compressedsize", 0, ResourceParam { name: "zip_entry", accepts_closed: false, closes: false, kind: None }),
    ("zip_entry_compressionmethod", 0, ResourceParam { name: "zip_entry", accepts_closed: false, closes: false, kind: None }),
    ("zip_entry_filesize", 0, ResourceParam { name: "zip_entry", accepts_closed: false, closes: false, kind: None }),
    ("zip_entry_name", 0, ResourceParam { name: "zip_entry", accepts_closed: false, closes: false, kind: None }),
    ("zip_entry_open", 0, ResourceParam { name: "zip_dp", accepts_closed: false, closes: false, kind: None }),
    ("zip_entry_open", 1, ResourceParam { name: "zip_entry", accepts_closed: false, closes: false, kind: None }),
    ("zip_entry_read", 0, ResourceParam { name: "zip_entry", accepts_closed: false, closes: false, kind: None }),
    ("zip_read", 0, ResourceParam { name: "zip", accepts_closed: false, closes: false, kind: None }),
];
