// @generated by `cargo xtask gen-catalog` from
// docs/research/phpsrc-mining/resource_returns.toml — DO NOT EDIT BY HAND.
//
// Builtins whose return is a legacy PHP RESOURCE (ADR-0056 §8): the one
// type PHP has no syntax to declare, so the reflected envelope every other
// return fact is anchored to can never carry it. A row is admitted at a
// call site only when all three §7 conditions hold — this table (the stub
// reading at the pin), the analyzing engine declaring NO return type for
// the name (the resource-to-object migration tripwire), and the project
// PHP minor equalling PINNED_PHP.
//
// Each row: (lowercased builtin name, whether the stub's `@return` carries
// a `false` arm). Sorted by key for binary search. Source of record is the
// TOML, which carries the per-row stub path and probe transcript.

pub(crate) static RESOURCE_RETURNS: &[(&str, bool)] = &[
    ("bzopen", true),
    ("fopen", true),
    ("fsockopen", true),
    ("gzopen", true),
    ("opendir", true),
    ("pfsockopen", true),
    ("pg_socket", true),
    ("popen", true),
    ("proc_open", true),
    ("socket_export_stream", true),
    ("stream_context_create", false),
    ("stream_context_get_default", false),
    ("stream_context_set_default", false),
    ("stream_filter_append", true),
    ("stream_filter_prepend", true),
    ("stream_socket_accept", true),
    ("stream_socket_client", true),
    ("stream_socket_server", true),
    ("tmpfile", true),
];
