// @generated by `cargo xtask gen-catalog` from
// docs/research/phpsrc-mining/return_facts.toml — DO NOT EDIT BY HAND.
//
// Builtin return-fact REFINEMENTS (ADR-0056): each row is a curated phpdoc
// type string that narrows strictly WITHIN a builtin's reflected return
// envelope. The reflected envelope itself is seeded without a row; a row is
// consumed only after the acceptance machinery confirms it is an extensional
// subset of the envelope AND the project PHP minor equals PINNED_PHP
// (ADR-0056 §2). The table may be empty — R1 lands zero rows (the bool
// family's envelope is already `bool`). Source of record is the TOML.
//
// Each row: (lowercased builtin name, curated refinement phpdoc string).
// Sorted by key for binary search.

pub(crate) static RETURN_FACTS: &[(&str, &str)] = &[
    ("array_push", "int<0, max>"),
    ("array_unshift", "int<0, max>"),
    ("count", "int<0, max>"),
    ("func_num_args", "int<0, max>"),
    ("get_debug_type", "non-falsy-string"),
    ("mb_strlen", "int<0, max>"),
    ("md5", "non-falsy-string"),
    ("sha1", "non-falsy-string"),
    ("sizeof", "int<0, max>"),
    ("spl_object_hash", "non-falsy-string"),
    ("strlen", "int<0, max>"),
    ("substr_count", "int<0, max>"),
    ("uniqid", "non-falsy-string"),
];
