// @generated by `cargo xtask gen-catalog` from
// docs/research/phpsrc-mining/return_facts.toml — DO NOT EDIT BY HAND.
//
// Builtin return-fact REFINEMENTS (ADR-0056): each row is a curated phpdoc
// type string that narrows strictly WITHIN a builtin's reflected return
// envelope. The reflected envelope itself is seeded without a row; a row is
// consumed only after the acceptance machinery confirms it is an extensional
// subset of the envelope AND the project PHP minor equals PINNED_PHP
// (ADR-0056 §2). The table may be empty — R1 lands zero rows (the bool
// family's envelope is already `bool`). Source of record is the TOML.
//
// Each row: (lowercased builtin name, curated refinement phpdoc string).
// Sorted by key for binary search.

pub(crate) static RETURN_FACTS: &[(&str, &str)] = &[
];
