//! The FP-gate corpus: the fixed package list (ADR-0021), the committed lock
//! file, and the file-collection logic shared by every command.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use steins_db::walk::Sources;

/// One corpus package: its Packagist-style name and its GitHub clone URL. The
/// list is fixed by ADR-0021 ("Initial FP-gate corpus").
pub struct Package {
    /// The `vendor/name` identity used in the lock file and reports.
    pub name: &'static str,
    /// The GitHub HTTPS clone URL (no `.git` suffix; git accepts either).
    pub repo: &'static str,
}

/// The ten packages of the initial FP-gate corpus (ADR-0021).
pub const PACKAGES: &[Package] = &[
    Package { name: "composer/composer", repo: "https://github.com/composer/composer" },
    Package { name: "sebastianbergmann/phpunit", repo: "https://github.com/sebastianbergmann/phpunit" },
    Package { name: "guzzle/guzzle", repo: "https://github.com/guzzle/guzzle" },
    Package { name: "Seldaek/monolog", repo: "https://github.com/Seldaek/monolog" },
    Package { name: "symfony/console", repo: "https://github.com/symfony/console" },
    Package { name: "symfony/process", repo: "https://github.com/symfony/process" },
    Package { name: "thephpleague/flysystem", repo: "https://github.com/thephpleague/flysystem" },
    Package { name: "nikic/PHP-Parser", repo: "https://github.com/nikic/PHP-Parser" },
    Package { name: "briannesbitt/Carbon", repo: "https://github.com/briannesbitt/Carbon" },
    Package { name: "cakephp/chronos", repo: "https://github.com/cakephp/chronos" },
];

/// The committed lock file (`corpus.lock.toml`) pinning every package to an
/// exact release tag and commit, so `fp-gate` and `freq` measure a reproducible
/// snapshot.
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Lock {
    #[serde(default, rename = "package")]
    pub packages: Vec<LockEntry>,
}

/// One pinned package in the lock file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockEntry {
    pub name: String,
    pub repo: String,
    pub tag: String,
    pub commit: String,
}

impl Lock {
    /// The lock entry for `name`, if present.
    pub fn get(&self, name: &str) -> Option<&LockEntry> {
        self.packages.iter().find(|e| e.name == name)
    }

    /// Insert or replace the entry for `entry.name`, keeping the file ordered by
    /// the canonical [`PACKAGES`] order for a stable diff.
    pub fn upsert(&mut self, entry: LockEntry) {
        if let Some(slot) = self.packages.iter_mut().find(|e| e.name == entry.name) {
            *slot = entry;
        } else {
            self.packages.push(entry);
        }
        self.packages.sort_by_key(|e| {
            PACKAGES.iter().position(|p| p.name == e.name).unwrap_or(usize::MAX)
        });
    }
}

/// The repo root (the directory containing this workspace's `Cargo.toml`),
/// derived from the xtask crate's manifest dir at compile time.
pub fn repo_root() -> PathBuf {
    // `CARGO_MANIFEST_DIR` is `<root>/xtask`; the parent is the workspace root.
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().expect("xtask has a parent dir").to_path_buf()
}

/// Path to the committed lock file.
pub fn lock_path() -> PathBuf {
    repo_root().join("corpus.lock.toml")
}

/// Read the lock file, or an empty lock if it does not exist yet.
pub fn read_lock() -> Lock {
    let path = lock_path();
    match std::fs::read_to_string(&path) {
        Ok(text) => toml::from_str(&text).unwrap_or_else(|e| {
            panic!("corpus.lock.toml is malformed ({e}); delete it to re-resolve")
        }),
        Err(_) => Lock::default(),
    }
}

/// Write the lock file with a short provenance header.
pub fn write_lock(lock: &Lock) {
    let body = toml::to_string_pretty(lock).expect("lock serializes");
    let text = format!(
        "# Pinned FP-gate corpus (ADR-0013/0021). Generated by `cargo xtask corpus-sync`.\n\
         # Each package is a shallow clone at exactly the tag+commit recorded here.\n\
         # Re-resolve to the latest stable release with `cargo xtask corpus-sync --update`.\n\n{body}"
    );
    std::fs::write(lock_path(), text).expect("write corpus.lock.toml");
}

/// The checkout directory for a package inside `corpus/` (gitignored). The
/// `vendor/name` is flattened to `vendor__name` so it is a single dir.
pub fn checkout_dir(name: &str) -> PathBuf {
    repo_root().join("corpus").join(name.replace('/', "__"))
}

/// The `.php` files under `dir`, sorted — **the walk the `steins` binary
/// itself does** ([`steins_db::walk`], issue #524).
///
/// It is not a second collector that agrees with the product by inspection: it
/// is the same code. Before #524 it was a second collector, and it disagreed —
/// over a 6,670-file corpus containing a `corpus/corpus` self-link the CLI
/// counted 13,340 files and this harness counted 220,110, so every whole-corpus
/// number the perf harness produced was measuring a universe the product would
/// never analyze. A harness that measures a different universe than the product
/// cannot inform the decisions it exists for.
pub fn collect_php_files(dir: &Path) -> Vec<PathBuf> {
    php_sources(dir).files
}

/// [`collect_php_files`] keeping the walk's posture — the directory symlinks it
/// refused, which a harness reports rather than silently walking past.
pub fn php_sources(dir: &Path) -> Sources {
    steins_db::walk::php_files(std::slice::from_ref(&dir.to_path_buf()))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The harness's universe is the product's universe (issue #524).
    ///
    /// The fixture is the shape that broke the ADR-0092 measurements: a
    /// directory symlink out of the tree, one back into it (`corpus/corpus`),
    /// and a file symlink. A human counting `.php` files here says two —
    /// `pkg/a.php` and `pkg/sub/b.php`, since `pkg/link.php` is `a.php` under
    /// another name — and that is what both this harness and `steins` itself
    /// must say. Before the fix this collector followed both directory links
    /// until the OS's symlink limit stopped it (33 spellings of every file),
    /// while the CLI's separate collector reported twice the tree.
    ///
    /// The CLI half of this pair is `crates/steins-cli/tests/symlink_walk.rs`,
    /// which asserts the same universe through the binary.
    #[cfg(unix)]
    #[test]
    fn the_harness_walks_the_tree_the_binary_walks() {
        use std::os::unix::fs::symlink;

        let dir = std::env::temp_dir().join(format!("steins-xtask-walk-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("outside")).unwrap();
        std::fs::create_dir_all(dir.join("tree/pkg/sub")).unwrap();
        std::fs::write(dir.join("outside/away.php"), "<?php\n").unwrap();
        std::fs::write(dir.join("tree/pkg/a.php"), "<?php\n").unwrap();
        std::fs::write(dir.join("tree/pkg/sub/b.php"), "<?php\n").unwrap();
        symlink(dir.join("outside"), dir.join("tree/out")).unwrap();
        symlink(dir.join("tree"), dir.join("tree/tree")).unwrap();
        symlink(dir.join("tree/pkg/a.php"), dir.join("tree/pkg/link.php")).unwrap();

        let sources = php_sources(&dir.join("tree"));
        let names: Vec<String> = sources
            .files
            .iter()
            .map(|f| f.strip_prefix(dir.join("tree")).unwrap().display().to_string())
            .collect();
        // Nothing under `out` or `tree/tree` is analyzed at all, and both are
        // counted rather than passed over in silence.
        assert_eq!(names, vec!["pkg/a.php", "pkg/sub/b.php"], "got {names:?}");
        assert_eq!(sources.skip_counts(), (1, 1), "skipped: {:?}", sources.skipped_links);

        let _ = std::fs::remove_dir_all(&dir);
    }
}
