//! The FP-gate corpus: the fixed package list (ADR-0021), the committed lock
//! file, and the file-collection logic shared by every command.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// One corpus package: its Packagist-style name and its GitHub clone URL. The
/// list is fixed by ADR-0021 ("Initial FP-gate corpus").
pub struct Package {
    /// The `vendor/name` identity used in the lock file and reports.
    pub name: &'static str,
    /// The GitHub HTTPS clone URL (no `.git` suffix; git accepts either).
    pub repo: &'static str,
}

/// The ten packages of the initial FP-gate corpus (ADR-0021).
pub const PACKAGES: &[Package] = &[
    Package { name: "composer/composer", repo: "https://github.com/composer/composer" },
    Package { name: "sebastianbergmann/phpunit", repo: "https://github.com/sebastianbergmann/phpunit" },
    Package { name: "guzzle/guzzle", repo: "https://github.com/guzzle/guzzle" },
    Package { name: "Seldaek/monolog", repo: "https://github.com/Seldaek/monolog" },
    Package { name: "symfony/console", repo: "https://github.com/symfony/console" },
    Package { name: "symfony/process", repo: "https://github.com/symfony/process" },
    Package { name: "thephpleague/flysystem", repo: "https://github.com/thephpleague/flysystem" },
    Package { name: "nikic/PHP-Parser", repo: "https://github.com/nikic/PHP-Parser" },
    Package { name: "briannesbitt/Carbon", repo: "https://github.com/briannesbitt/Carbon" },
    Package { name: "cakephp/chronos", repo: "https://github.com/cakephp/chronos" },
];

/// The committed lock file (`corpus.lock.toml`) pinning every package to an
/// exact release tag and commit, so `fp-gate` and `freq` measure a reproducible
/// snapshot.
#[derive(Debug, Default, Serialize, Deserialize)]
pub struct Lock {
    #[serde(default, rename = "package")]
    pub packages: Vec<LockEntry>,
}

/// One pinned package in the lock file.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockEntry {
    pub name: String,
    pub repo: String,
    pub tag: String,
    pub commit: String,
}

impl Lock {
    /// The lock entry for `name`, if present.
    pub fn get(&self, name: &str) -> Option<&LockEntry> {
        self.packages.iter().find(|e| e.name == name)
    }

    /// Insert or replace the entry for `entry.name`, keeping the file ordered by
    /// the canonical [`PACKAGES`] order for a stable diff.
    pub fn upsert(&mut self, entry: LockEntry) {
        if let Some(slot) = self.packages.iter_mut().find(|e| e.name == entry.name) {
            *slot = entry;
        } else {
            self.packages.push(entry);
        }
        self.packages.sort_by_key(|e| {
            PACKAGES.iter().position(|p| p.name == e.name).unwrap_or(usize::MAX)
        });
    }
}

/// The repo root (the directory containing this workspace's `Cargo.toml`),
/// derived from the xtask crate's manifest dir at compile time.
pub fn repo_root() -> PathBuf {
    // `CARGO_MANIFEST_DIR` is `<root>/xtask`; the parent is the workspace root.
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().expect("xtask has a parent dir").to_path_buf()
}

/// Path to the committed lock file.
pub fn lock_path() -> PathBuf {
    repo_root().join("corpus.lock.toml")
}

/// Read the lock file, or an empty lock if it does not exist yet.
pub fn read_lock() -> Lock {
    let path = lock_path();
    match std::fs::read_to_string(&path) {
        Ok(text) => toml::from_str(&text).unwrap_or_else(|e| {
            panic!("corpus.lock.toml is malformed ({e}); delete it to re-resolve")
        }),
        Err(_) => Lock::default(),
    }
}

/// Write the lock file with a short provenance header.
pub fn write_lock(lock: &Lock) {
    let body = toml::to_string_pretty(lock).expect("lock serializes");
    let text = format!(
        "# Pinned FP-gate corpus (ADR-0013/0021). Generated by `cargo xtask corpus-sync`.\n\
         # Each package is a shallow clone at exactly the tag+commit recorded here.\n\
         # Re-resolve to the latest stable release with `cargo xtask corpus-sync --update`.\n\n{body}"
    );
    std::fs::write(lock_path(), text).expect("write corpus.lock.toml");
}

/// The checkout directory for a package inside `corpus/` (gitignored). The
/// `vendor/name` is flattened to `vendor__name` so it is a single dir.
pub fn checkout_dir(name: &str) -> PathBuf {
    repo_root().join("corpus").join(name.replace('/', "__"))
}

/// Recursively collect `.php` files under `dir`, skipping VCS metadata.
pub fn collect_php_files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|n| n == ".git") {
                continue;
            }
            collect_php_files(&path, out);
        } else if path.extension().is_some_and(|e| e == "php") {
            out.push(path);
        }
    }
}
