//! `freq`: builtin-call frequency over the corpus (ADR-0021 seeding order).
//!
//! # Methodology (whole-project revision)
//!
//! Each corpus package is now loaded as ONE project (one salsa DB), so
//! [`steins_infer::resolves_to_user_function`] can resolve every function call
//! against the project symbol index using PHP name resolution (namespace
//! fallback + `use` imports). A call is counted **only when it does not resolve
//! to a userland function defined anywhere in its package** — so cross-file
//! userland calls (previously counted as an upper-bound contaminant) are now
//! excluded. The result is a *true builtin ranking*: what remains is builtins
//! and genuinely-unresolved names, which is exactly the signal that should drive
//! the catalog's effect-coloring order. Names are folded case-insensitively by
//! last namespace segment.

use std::collections::HashMap;

use rayon::prelude::*;
use steins_db::{Project, SourceFile, SteinsDatabase, parse, project_index};
use steins_infer::resolves_to_user_function;

use crate::corpus::{PACKAGES, checkout_dir, collect_php_files, read_lock, repo_root};

const TOP_N: usize = 300;

/// Entry point for `cargo xtask freq`.
pub fn run() -> Result<(), String> {
    let lock = read_lock();
    if lock.packages.is_empty() {
        return Err("corpus.lock.toml is empty — run `cargo xtask corpus-sync` first".to_owned());
    }

    for pkg in PACKAGES {
        let dir = checkout_dir(pkg.name);
        if !dir.is_dir() {
            return Err(format!("{} not checked out — run `cargo xtask corpus-sync`", pkg.name));
        }
    }

    // Each package is its own project; count in parallel across packages, then
    // merge. Resolution against the package's project index removes userland
    // cross-file calls.
    let (counts, file_count): (HashMap<String, u64>, usize) = PACKAGES
        .par_iter()
        .map(|pkg| count_package(&checkout_dir(pkg.name)))
        .reduce(
            || (HashMap::new(), 0usize),
            |mut a, b| {
                for (k, v) in b.0 {
                    *a.0.entry(k).or_insert(0) += v;
                }
                a.1 += b.1;
                a
            },
        );

    let grand_total: u64 = counts.values().sum();
    let distinct = counts.len();

    // Rank: count desc, then name asc for a stable order.
    let mut ranked: Vec<(String, u64)> = counts.into_iter().collect();
    ranked.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));

    let report = render_markdown(&ranked, grand_total, distinct, file_count, &lock);
    let out_path = repo_root().join("docs/notes/20260722-builtin-frequency.md");
    std::fs::write(&out_path, report).map_err(|e| format!("write {}: {e}", out_path.display()))?;

    println!(
        "freq: {} files, {grand_total} counted calls, {distinct} distinct callees → {}",
        file_count,
        out_path.display()
    );
    // Echo the top 20 so the run is self-documenting.
    println!("\nrank  count  name");
    for (i, (name, count)) in ranked.iter().take(20).enumerate() {
        println!("{:>4}  {:>5}  {name}", i + 1, count);
    }
    Ok(())
}

/// Count one package's non-userland calls, resolved against the package project.
/// Returns the count map and the number of files seen.
fn count_package(dir: &std::path::Path) -> (HashMap<String, u64>, usize) {
    let mut counts: HashMap<String, u64> = HashMap::new();
    let mut files = Vec::new();
    collect_php_files(dir, &mut files);

    let db = SteinsDatabase::default();
    let inputs: Vec<SourceFile> = files
        .iter()
        .map(|f| {
            let text = std::fs::read(f)
                .map(|b| String::from_utf8_lossy(&b).into_owned())
                .unwrap_or_default();
            SourceFile::new(&db, f.to_string_lossy().into_owned(), text)
        })
        .collect();
    let project = Project::new(&db, inputs.clone());
    let index = project_index(&db, project);

    for &input in &inputs {
        let tree = parse(&db, input);
        for call in tree.calls() {
            let Some(r) = call.callee_ref.as_ref() else { continue };
            // Exclude calls that resolve to a userland function in the project.
            if resolves_to_user_function(index, tree, r) {
                continue;
            }
            let name = r.simple().trim_start_matches('\\').to_ascii_lowercase();
            if name.is_empty() {
                continue;
            }
            *counts.entry(name).or_insert(0) += 1;
        }
    }
    (counts, files.len())
}

fn render_markdown(
    ranked: &[(String, u64)],
    grand_total: u64,
    distinct: usize,
    file_count: usize,
    lock: &crate::corpus::Lock,
) -> String {
    let mut s = String::new();
    s.push_str("# Builtin-call frequency over the FP-gate corpus\n\n");
    s.push_str(
        "Generated by `cargo run -p xtask -- freq`. This measurement feeds ADR-0021's \
         catalog seeding order: effect coloring follows *measured demand*, so the most \
         frequently called builtins are colored first, top-down. Uncolored functions \
         widen to unknown-effect (a miss, never a false positive), the only seeding order \
         compatible with the zero-FP bar (ADR-0002).\n\n",
    );
    s.push_str(
        "**Methodology change (whole-project resolution).** Each package is now loaded as \
         one project, and every call is resolved against the project symbol index using \
         PHP name resolution (namespace fallback + `use` imports). A call is counted only \
         when it does **not** resolve to a userland function defined anywhere in its \
         package — so cross-file userland calls are excluded and this ranking is a *true \
         builtin ranking*, no longer the old upper bound. What remains is builtins and \
         genuinely-unresolved names. Names are folded case-insensitively by last \
         namespace segment.\n\n",
    );
    s.push_str(&format!(
        "- Files analyzed: {file_count}\n- Counted cross-file calls: {grand_total}\n- Distinct callees: {distinct}\n\n"
    ));
    s.push_str("Measured at the corpus pinned in `corpus.lock.toml`:\n\n");
    for e in &lock.packages {
        s.push_str(&format!("- `{}` @ {} ({})\n", e.name, e.tag, &e.commit[..e.commit.len().min(12)]));
    }
    s.push_str(&format!("\n## Top {TOP_N} callees\n\n"));
    s.push_str("| rank | name | count | cumulative % |\n");
    s.push_str("|-----:|------|------:|-------------:|\n");

    let mut running: u64 = 0;
    for (i, (name, count)) in ranked.iter().take(TOP_N).enumerate() {
        running += *count;
        let cum = if grand_total == 0 { 0.0 } else { running as f64 / grand_total as f64 * 100.0 };
        s.push_str(&format!("| {} | `{}` | {} | {:.2}% |\n", i + 1, name, count, cum));
    }
    s.push('\n');
    s
}
