//! `freq`: builtin-call frequency over the corpus (ADR-0021 seeding order).
//!
//! Counts call expressions whose callee is *not* a function declared in the same
//! file. PHP function names are case-insensitive, and the lowered callee is
//! already the last namespace segment (`Foo\bar()` → `bar`), so we fold by
//! lowercased last segment. The top of the resulting list drives the catalog's
//! effect-coloring order. Because we cannot yet resolve userland cross-file
//! functions, they are still counted here — the list is an *upper bound* to be
//! filtered against the real php-src builtin list later.

use std::collections::HashMap;
use std::path::PathBuf;

use rayon::prelude::*;
use steins_syntax::SourceTree;

use crate::corpus::{PACKAGES, checkout_dir, collect_php_files, read_lock, repo_root};

const TOP_N: usize = 300;

/// Entry point for `cargo xtask freq`.
pub fn run() -> Result<(), String> {
    let lock = read_lock();
    if lock.packages.is_empty() {
        return Err("corpus.lock.toml is empty — run `cargo xtask corpus-sync` first".to_owned());
    }

    // Gather every corpus file up front so the whole set parallelizes evenly.
    let mut files: Vec<PathBuf> = Vec::new();
    for pkg in PACKAGES {
        let dir = checkout_dir(pkg.name);
        if !dir.is_dir() {
            return Err(format!(
                "{} not checked out — run `cargo xtask corpus-sync`",
                pkg.name
            ));
        }
        collect_php_files(&dir, &mut files);
    }

    // Fold each file to a local count map, then merge. Ignores files with parse
    // errors for their *un-parsed* tail only — recovered calls still count.
    let counts: HashMap<String, u64> = files
        .par_iter()
        .fold(HashMap::new, |mut acc, path| {
            if let Ok(bytes) = std::fs::read(path) {
                let text = String::from_utf8_lossy(&bytes);
                count_file(&text, &mut acc);
            }
            acc
        })
        .reduce(HashMap::new, |mut a, b| {
            for (k, v) in b {
                *a.entry(k).or_insert(0) += v;
            }
            a
        });

    let grand_total: u64 = counts.values().sum();
    let distinct = counts.len();

    // Rank: count desc, then name asc for a stable order.
    let mut ranked: Vec<(String, u64)> = counts.into_iter().collect();
    ranked.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.cmp(&b.0)));

    let report = render_markdown(&ranked, grand_total, distinct, files.len(), &lock);
    let out_path = repo_root().join("docs/notes/20260722-builtin-frequency.md");
    std::fs::write(&out_path, report).map_err(|e| format!("write {}: {e}", out_path.display()))?;

    println!(
        "freq: {} files, {grand_total} counted calls, {distinct} distinct callees → {}",
        files.len(),
        out_path.display()
    );
    // Echo the top 20 so the run is self-documenting.
    println!("\nrank  count  name");
    for (i, (name, count)) in ranked.iter().take(20).enumerate() {
        println!("{:>4}  {:>5}  {name}", i + 1, count);
    }
    Ok(())
}

/// Add one file's cross-file call counts into `acc`.
fn count_file(text: &str, acc: &mut HashMap<String, u64>) {
    let tree = SourceTree::parse(text);

    // Same-file user function names, lowercased (PHP is case-insensitive).
    let local: std::collections::HashSet<String> =
        tree.functions().iter().map(|f| f.name.to_ascii_lowercase()).collect();

    for call in tree.calls() {
        let Some(callee) = call.callee.as_deref() else { continue };
        // Defensive: strip any leading namespace separators (the lowering already
        // reduces to the last segment, but a stray `\strlen` should still fold).
        let name = callee.trim_start_matches('\\').to_ascii_lowercase();
        if name.is_empty() || local.contains(&name) {
            continue;
        }
        *acc.entry(name).or_insert(0) += 1;
    }
}

fn render_markdown(
    ranked: &[(String, u64)],
    grand_total: u64,
    distinct: usize,
    file_count: usize,
    lock: &crate::corpus::Lock,
) -> String {
    let mut s = String::new();
    s.push_str("# Builtin-call frequency over the FP-gate corpus\n\n");
    s.push_str(
        "Generated by `cargo run -p xtask -- freq`. This measurement feeds ADR-0021's \
         catalog seeding order: effect coloring follows *measured demand*, so the most \
         frequently called builtins are colored first, top-down. Uncolored functions \
         widen to unknown-effect (a miss, never a false positive), the only seeding order \
         compatible with the zero-FP bar (ADR-0002).\n\n",
    );
    s.push_str(
        "**Upper bound, not a builtin list.** A callee is counted when it is *not* a \
         function declared in the same file, but we cannot yet resolve userland \
         cross-file functions — those are still counted here. Treat this ranking as an \
         upper bound to be filtered against the real php-src builtin list before it drives \
         coloring. Names are folded case-insensitively by last namespace segment.\n\n",
    );
    s.push_str(&format!(
        "- Files analyzed: {file_count}\n- Counted cross-file calls: {grand_total}\n- Distinct callees: {distinct}\n\n"
    ));
    s.push_str("Measured at the corpus pinned in `corpus.lock.toml`:\n\n");
    for e in &lock.packages {
        s.push_str(&format!("- `{}` @ {} ({})\n", e.name, e.tag, &e.commit[..e.commit.len().min(12)]));
    }
    s.push_str(&format!("\n## Top {TOP_N} callees\n\n"));
    s.push_str("| rank | name | count | cumulative % |\n");
    s.push_str("|-----:|------|------:|-------------:|\n");

    let mut running: u64 = 0;
    for (i, (name, count)) in ranked.iter().take(TOP_N).enumerate() {
        running += *count;
        let cum = if grand_total == 0 { 0.0 } else { running as f64 / grand_total as f64 * 100.0 };
        s.push_str(&format!("| {} | `{}` | {} | {:.2}% |\n", i + 1, name, count, cum));
    }
    s.push('\n');
    s
}
