//! `phpdoc-oracle`: the differential compatibility check for `steins-phpdoc`
//! (ADR-0029). It runs the *real* phpstan/phpdoc-parser (via the PHP sidecar in
//! `harness/phpdoc-oracle/dump.php`) as an oracle and diffs it against our parser
//! over two sources:
//!
//!   (a) the ported reference fixtures — regenerating `reference-types.expected`,
//!       or, with `--check`, diffing instead of writing (CI mode);
//!   (b) every `@param`/`@return`/`@var`/`@throws` type expression extracted from
//!       the public corpus `.php` files — printing any disagreement verbatim.
//!
//! A disagreement where we parse *differently* (a wrong parse) is a bug and fails
//! the command; a disagreement where we say "unsupported/error" while the
//! reference accepts is a coverage gap — counted, not failed (silence is safe).
//!
//! Requires `php` + `composer` and an installed harness `vendor/`. When any is
//! absent the command prints a clear message and succeeds (it is optional tooling,
//! never a hard gate on machines without PHP).

use std::collections::BTreeMap;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use steins_phpdoc::{TypeKind, parse_type, scan_docblock};

use crate::corpus::{collect_php_files, repo_root};

/// Entry point for `cargo xtask phpdoc-oracle [--check]`.
pub fn run(check: bool) -> Result<(), String> {
    let root = repo_root();
    let harness = root.join("harness").join("phpdoc-oracle");
    let dump = harness.join("dump.php");
    let vendor = harness.join("vendor").join("autoload.php");

    if !dump.is_file() {
        return Err(format!("oracle script not found at {}", dump.display()));
    }
    if which("php").is_none() {
        println!("phpdoc-oracle: `php` not on PATH — skipping (optional tooling).");
        return Ok(());
    }
    if !vendor.is_file() {
        println!(
            "phpdoc-oracle: harness vendor/ missing — run `composer install` in {} — skipping.",
            harness.display()
        );
        return Ok(());
    }

    let phpdoc_version = read_phpdoc_version(&harness).unwrap_or_else(|| "unknown".to_owned());
    println!("phpdoc-oracle: reference = phpstan/phpdoc-parser {phpdoc_version}\n");

    // (a) Fixtures: regenerate or --check.
    fixtures_stage(&root, &harness, &dump, &phpdoc_version, check)?;

    // (b) Corpus docblocks: differential diff.
    corpus_stage(&root, &harness, &dump)
}

// ----------------------------------------------------------------------------
// (a) fixtures
// ----------------------------------------------------------------------------

fn fixtures_stage(
    root: &Path,
    harness: &Path,
    dump: &Path,
    phpdoc_version: &str,
    check: bool,
) -> Result<(), String> {
    let fixtures_dir = root
        .join("crates")
        .join("steins-phpdoc")
        .join("tests")
        .join("fixtures");
    let txt = fixtures_dir.join("reference-types.txt");
    let expected = fixtures_dir.join("reference-types.expected");

    // Read as bytes: the corpus carries one non-UTF-8 identifier line the raw
    // reference suite contains. dump.php does its own C-unescaping.
    // Read as bytes: the corpus carries one non-UTF-8 identifier line the raw
    // reference suite contains. dump.php does its own C-unescaping, and returns
    // bytes so the one 0xA0-bearing verdict round-trips byte-faithfully.
    let inputs = std::fs::read(&txt).map_err(|e| format!("cannot read {}: {e}", txt.display()))?;
    let verdicts = run_oracle(harness, dump, &inputs)?;

    let header = format!(
        "# steins-phpdoc reference oracle output — phpstan/phpdoc-parser {phpdoc_version}\n\
         # Generated by harness/phpdoc-oracle/dump.php from reference-types.txt (ADR-0029).\n\
         # Format per line: OK<TAB>canonical | PARTIAL<TAB>canonical | ERROR<TAB>message\n"
    );
    let mut new_contents: Vec<u8> = header.into_bytes();
    new_contents.extend_from_slice(verdicts.strip_suffix(b"\n").unwrap_or(&verdicts));
    new_contents.push(b'\n');

    if check {
        let current = std::fs::read(&expected)
            .map_err(|e| format!("cannot read {}: {e}", expected.display()))?;
        // Compare verdict lines only (ignore the header, whose version text may
        // drift independently of behaviour). Lossy is fine: both sides carry the
        // same replacement char for the lone non-UTF-8 verdict.
        let cur_s = String::from_utf8_lossy(&current).into_owned();
        let new_s = String::from_utf8_lossy(&new_contents).into_owned();
        let cur_body = strip_comment_lines(&cur_s);
        let new_body_only = strip_comment_lines(&new_s);
        if cur_body != new_body_only {
            let diff = first_diff(&cur_body, &new_body_only);
            return Err(format!(
                "fixtures out of date: {}\n  committed vs oracle diff:\n{diff}\n\
                 run `cargo xtask phpdoc-oracle` (without --check) to regenerate.",
                expected.display()
            ));
        }
        println!("fixtures: reference-types.expected is up to date ({} verdicts).", cur_body.len());
    } else {
        std::fs::write(&expected, &new_contents)
            .map_err(|e| format!("cannot write {}: {e}", expected.display()))?;
        let n = String::from_utf8_lossy(&new_contents)
            .lines()
            .filter(|l| !l.is_empty() && !l.starts_with('#'))
            .count();
        println!("fixtures: wrote {} verdicts to {}.", n, expected.display());
    }
    Ok(())
}

fn strip_comment_lines(s: &str) -> Vec<&str> {
    s.lines()
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .collect()
}

fn first_diff(a: &[&str], b: &[&str]) -> String {
    for (i, (x, y)) in a.iter().zip(b).enumerate() {
        if x != y {
            return format!("    line {}: committed `{x}` vs oracle `{y}`", i + 1);
        }
    }
    if a.len() != b.len() {
        return format!("    line count differs: committed {} vs oracle {}", a.len(), b.len());
    }
    String::new()
}

// ----------------------------------------------------------------------------
// (b) corpus
// ----------------------------------------------------------------------------

fn corpus_stage(root: &Path, harness: &Path, dump: &Path) -> Result<(), String> {
    let corpus = root.join("corpus");
    if !corpus.is_dir() {
        println!("\ncorpus: {} not present — run `cargo xtask corpus-sync` — skipping corpus diff.", corpus.display());
        return Ok(());
    }

    let mut files = Vec::new();
    collect_php_files(&corpus, &mut files);
    files.sort();
    println!("\ncorpus: scanning {} .php files for docblock types…", files.len());

    // Extract unique type strings (dedup keeps the oracle batch small; we track
    // total occurrences for reporting).
    let mut occurrences: BTreeMap<String, usize> = BTreeMap::new();
    for f in &files {
        let Ok(text) = std::fs::read_to_string(f) else {
            continue; // non-UTF-8 file: skip (rare; safe)
        };
        for block in docblocks(&text) {
            for tag in scan_docblock(block) {
                // Parse only the type prefix our parser consumes, so the string
                // handed to the oracle is the type itself (not the description).
                let type_str = leading_type_string(&tag.type_text);
                if type_str.is_empty() {
                    continue;
                }
                *occurrences.entry(type_str).or_insert(0) += 1;
            }
        }
    }

    let unique: Vec<String> = occurrences.keys().cloned().collect();
    let total_occurrences: usize = occurrences.values().sum();
    if unique.is_empty() {
        println!("corpus: no docblock type expressions found.");
        return Ok(());
    }

    // Run the oracle over all unique type strings in one batch.
    let batch = unique
        .iter()
        .map(|s| c_escape(s))
        .collect::<Vec<_>>()
        .join("\n");
    let verdicts_bytes = run_oracle(harness, dump, batch.as_bytes())?;
    let verdicts_raw = String::from_utf8_lossy(&verdicts_bytes).into_owned();
    let ref_verdicts: Vec<&str> = verdicts_raw.lines().collect();
    if ref_verdicts.len() != unique.len() {
        return Err(format!(
            "oracle returned {} lines for {} inputs",
            ref_verdicts.len(),
            unique.len()
        ));
    }

    let mut agree = 0usize;
    let mut unsupported = 0usize;
    let mut disagreements: Vec<String> = Vec::new();

    for (input, refline) in unique.iter().zip(&ref_verdicts) {
        let refv = RefVerdict::parse(refline);
        let ours = OurVerdict::of(input);
        match classify(&refv, &ours) {
            Class::Agree => agree += 1,
            Class::CoverageGap => unsupported += 1,
            Class::Wrong(msg) => disagreements.push(format!(
                "  `{}` (x{}): {msg}",
                input,
                occurrences.get(input).copied().unwrap_or(0)
            )),
        }
    }

    println!("\n=== corpus docblock differential ===");
    println!("unique type expressions: {}", unique.len());
    println!("total occurrences:       {total_occurrences}");
    println!(
        "agreement:               {agree}  ({:.1}% of unique)",
        100.0 * agree as f64 / unique.len() as f64
    );
    println!("unsupported (silent):    {unsupported}");
    println!("wrong-parse disagreements:{}", disagreements.len());

    if !disagreements.is_empty() {
        println!("\ndisagreements (wrong parses — must be zero):");
        for d in &disagreements {
            println!("{d}");
        }
        return Err(format!(
            "{} wrong-parse disagreement(s) over the corpus — fix the parser.",
            disagreements.len()
        ));
    }
    println!("\nphpdoc-oracle: GREEN — zero wrong-parse disagreements over the corpus.");
    Ok(())
}

/// Return the byte-slice type prefix our parser consumes from `text` (the type,
/// without any trailing `$var`/description), as an owned trimmed string.
fn leading_type_string(text: &str) -> String {
    match parse_type(text) {
        Ok(p) => text[..p.consumed as usize].trim().to_owned(),
        // If we cannot parse it at all, hand the whole (trimmed) candidate to the
        // oracle so a genuine parser gap still surfaces in the diff.
        Err(_) => text.trim().to_owned(),
    }
}

/// Yield each `/** … */` docblock body found in `text` (delimiters included).
fn docblocks(text: &str) -> Vec<&str> {
    let bytes = text.as_bytes();
    let mut blocks = Vec::new();
    let mut i = 0;
    while i + 2 < bytes.len() {
        if &bytes[i..i + 3] == b"/**" {
            // Find the closing `*/`.
            let mut j = i + 3;
            while j + 1 < bytes.len() && !(bytes[j] == b'*' && bytes[j + 1] == b'/') {
                j += 1;
            }
            let end = (j + 2).min(bytes.len());
            blocks.push(&text[i..end]);
            i = end;
        } else {
            i += 1;
        }
    }
    blocks
}

// ----------------------------------------------------------------------------
// verdict classification (shared shape with the crate's reference-corpus test)
// ----------------------------------------------------------------------------

enum RefVerdict {
    Ok(String),
    Partial(String),
    Error,
}

impl RefVerdict {
    fn parse(line: &str) -> RefVerdict {
        if let Some(r) = line.strip_prefix("OK\t") {
            RefVerdict::Ok(r.to_owned())
        } else if let Some(r) = line.strip_prefix("PARTIAL\t") {
            RefVerdict::Partial(r.to_owned())
        } else {
            RefVerdict::Error
        }
    }
}

enum OurVerdict {
    Ok(String),
    Partial(String),
    Error,
    Unsupported,
}

impl OurVerdict {
    fn of(input: &str) -> OurVerdict {
        match parse_type(input) {
            Ok(p) => {
                if matches!(p.ty.kind, TypeKind::Unsupported(_)) {
                    OurVerdict::Unsupported
                } else if p.at_end {
                    OurVerdict::Ok(escape_controls(&p.ty.to_string()))
                } else {
                    OurVerdict::Partial(escape_controls(&p.ty.to_string()))
                }
            }
            Err(_) => OurVerdict::Error,
        }
    }
}

enum Class {
    Agree,
    CoverageGap,
    Wrong(String),
}

fn classify(refv: &RefVerdict, ours: &OurVerdict) -> Class {
    match (refv, ours) {
        (RefVerdict::Error, OurVerdict::Error | OurVerdict::Unsupported) => Class::Agree,
        (RefVerdict::Error, OurVerdict::Ok(c) | OurVerdict::Partial(c)) => {
            Class::Wrong(format!("reference REJECTS, we produced `{c}`"))
        }
        (RefVerdict::Ok(rc), OurVerdict::Ok(oc)) => {
            if rc == oc {
                Class::Agree
            } else {
                Class::Wrong(format!("reference `{rc}` vs ours `{oc}`"))
            }
        }
        (RefVerdict::Partial(rc), OurVerdict::Partial(oc)) => {
            if rc == oc {
                Class::Agree
            } else {
                Class::Wrong(format!("partial: reference `{rc}` vs ours `{oc}`"))
            }
        }
        (RefVerdict::Ok(_) | RefVerdict::Partial(_), OurVerdict::Error | OurVerdict::Unsupported) => {
            Class::CoverageGap
        }
        (RefVerdict::Ok(rc), OurVerdict::Partial(oc)) => {
            Class::Wrong(format!("reference fully parses `{rc}`, we stopped early at `{oc}`"))
        }
        (RefVerdict::Partial(rc), OurVerdict::Ok(oc)) => {
            Class::Wrong(format!("reference partial `{rc}`, we consumed all as `{oc}`"))
        }
    }
}

fn escape_controls(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn c_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

// ----------------------------------------------------------------------------
// PHP subprocess plumbing
// ----------------------------------------------------------------------------

/// Run `php dump.php`, feeding `input` (C-escaped lines) on stdin and returning
/// its stdout verdict lines.
fn run_oracle(harness: &Path, dump: &Path, input: &[u8]) -> Result<Vec<u8>, String> {
    let mut child = Command::new("php")
        .arg(dump)
        .current_dir(harness)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("failed to spawn php: {e}"))?;

    {
        let mut stdin = child.stdin.take().ok_or("no stdin on php child")?;
        stdin
            .write_all(input)
            .map_err(|e| format!("writing to php stdin: {e}"))?;
    }

    let out = child
        .wait_with_output()
        .map_err(|e| format!("waiting on php: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "dump.php exited with {}: {}",
            out.status,
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    Ok(out.stdout)
}

/// Read the installed phpstan/phpdoc-parser version from the harness lock file.
fn read_phpdoc_version(harness: &Path) -> Option<String> {
    let lock = std::fs::read_to_string(harness.join("composer.lock")).ok()?;
    let idx = lock.find("\"phpstan/phpdoc-parser\"")?;
    let after = &lock[idx..];
    let vpos = after.find("\"version\"")?;
    let vslice = &after[vpos..];
    let start = vslice.find(':')?;
    let q1 = vslice[start..].find('"')? + start + 1;
    let q2 = vslice[q1..].find('"')? + q1;
    Some(vslice[q1..q2].to_owned())
}

/// A minimal `which`: is `cmd` runnable? (`--version` returns success on php).
fn which(cmd: &str) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    for dir in std::env::split_paths(&path) {
        let candidate = dir.join(cmd);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}
