//! The ported reference test corpus (ADR-0029): every type-expression input from
//! phpstan/phpdoc-parser's `TypeParserTest` data provider, paired with the verdict
//! the *real* parser produces (generated by `harness/phpdoc-oracle/dump.php`).
//!
//! For each fixture, our parser's verdict must be *compatible* with the reference:
//!
//! - reference parses OK / PARTIAL and we also produce a type → our canonical
//!   rendering (`Display`) and our consumed/at-end classification must match
//!   **exactly**. A different-but-well-formed rendering is a FAILURE (a wrong
//!   parse = a wrong envelope = a false-positive vector).
//! - reference parses OK / PARTIAL but the construct is outside our subset → we
//!   must yield an error or an `Unsupported` node (silence). Counted as a
//!   coverage gap, not a failure.
//! - reference errors → we must also error (or be unsupported). Accepting a type
//!   the reference rejects is a FAILURE.
//!
//! The subset-coverage ratio (exact matches / total) is printed. Zero wrong-parse
//! failures is the hard invariant; the coverage number is informational.

use std::fmt::Write as _;

use steins_phpdoc::{TypeKind, parse_type};

/// A reference verdict parsed from a `.expected` line.
#[derive(Debug, Clone, PartialEq, Eq)]
enum RefVerdict {
    /// Parsed, entire input consumed. Payload is the canonical `__toString`.
    Ok(String),
    /// Parsed a prefix, trailing tokens remain. Payload is the canonical form.
    Partial(String),
    /// The reference parser rejected the input.
    Error,
}

/// Our parser's verdict for the same input.
#[derive(Debug, Clone, PartialEq, Eq)]
enum OurVerdict {
    Ok(String),
    Partial(String),
    Error,
    /// Produced an `Unsupported` node — silence, safe.
    Unsupported,
    /// Input line was not valid UTF-8 (Rust cannot ingest it as `&str`): skipped.
    NonUtf8,
}

fn c_unescape(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = String::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'\\' && i + 1 < bytes.len() {
            match bytes[i + 1] {
                b'n' => out.push('\n'),
                b'r' => out.push('\r'),
                b't' => out.push('\t'),
                b'\\' => out.push('\\'),
                other => {
                    out.push('\\');
                    out.push(other as char);
                }
            }
            i += 2;
        } else {
            out.push(bytes[i] as char);
            i += 1;
        }
    }
    out
}

fn parse_ref_verdict(line: &str) -> RefVerdict {
    if let Some(rest) = line.strip_prefix("OK\t") {
        RefVerdict::Ok(rest.to_owned())
    } else if let Some(rest) = line.strip_prefix("PARTIAL\t") {
        RefVerdict::Partial(rest.to_owned())
    } else if line.starts_with("ERROR\t") {
        RefVerdict::Error
    } else {
        panic!("malformed .expected line: {line:?}");
    }
}

/// Escape literal control chars so the canonical form stays single-line (matching
/// the escaping `dump.php` applies to the reference `__toString`).
fn escape_controls(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn contains_unsupported(kind: &TypeKind) -> bool {
    // The parser never emits Unsupported for the reference grammar today, but the
    // classifier honours it so future opaque constructs count as coverage gaps.
    matches!(kind, TypeKind::Unsupported(_))
}

fn our_verdict(input_line_bytes: &[u8]) -> OurVerdict {
    let input = match std::str::from_utf8(input_line_bytes) {
        Ok(s) => s,
        Err(_) => return OurVerdict::NonUtf8,
    };
    let input = c_unescape(input);
    match parse_type(&input) {
        Ok(p) => {
            if contains_unsupported(&p.ty.kind) {
                return OurVerdict::Unsupported;
            }
            let canon = escape_controls(&p.ty.to_string());
            if p.at_end {
                OurVerdict::Ok(canon)
            } else {
                OurVerdict::Partial(canon)
            }
        }
        Err(_) => OurVerdict::Error,
    }
}

#[test]
fn reference_corpus_compatibility() {
    // Read both fixtures as bytes: the input file contains one non-UTF-8 line (a
    // raw 0xA0 identifier byte from the reference suite) we cannot feed as `&str`.
    let inputs_raw = include_bytes!("fixtures/reference-types.txt");
    let expected_raw = include_bytes!("fixtures/reference-types.expected");

    let input_lines: Vec<&[u8]> = split_lines(inputs_raw);
    // The .expected file has comment/blank header lines aligned with nothing in
    // the input; filter comments/blanks out and keep verdict lines in order.
    let expected_lines: Vec<String> = split_lines(expected_raw)
        .into_iter()
        .filter(|l| !l.is_empty() && l[0] != b'#')
        .map(|l| String::from_utf8_lossy(l).into_owned())
        .collect();

    // Drop trailing empty input line (from a final newline).
    let input_lines: Vec<&[u8]> = input_lines
        .into_iter()
        .filter(|l| !l.is_empty())
        .collect();

    assert_eq!(
        input_lines.len(),
        expected_lines.len(),
        "fixture .txt and .expected are misaligned ({} inputs vs {} verdicts)",
        input_lines.len(),
        expected_lines.len()
    );

    let total = input_lines.len();
    let mut matched = 0usize; // exact agreement (canonical match or error match)
    let mut coverage_gap = 0usize; // reference accepts, we're silent (error/unsupported)
    let mut non_utf8 = 0usize;
    let mut failures: Vec<String> = Vec::new();

    for (raw_input, exp_line) in input_lines.iter().zip(&expected_lines) {
        let refv = parse_ref_verdict(exp_line);
        let ours = our_verdict(raw_input);
        let input_disp = String::from_utf8_lossy(raw_input).into_owned();

        match (&refv, &ours) {
            // Skipped: cannot ingest as UTF-8. Not counted for or against.
            (_, OurVerdict::NonUtf8) => non_utf8 += 1,

            // Reference errors → we must not produce a type.
            (RefVerdict::Error, OurVerdict::Error | OurVerdict::Unsupported) => matched += 1,
            (RefVerdict::Error, OurVerdict::Ok(c) | OurVerdict::Partial(c)) => {
                failures.push(format!(
                    "WRONG-ACCEPT `{input_disp}`: reference REJECTS, we produced `{c}`"
                ));
            }

            // Reference accepts → we match, or we stay silent (coverage gap).
            (RefVerdict::Ok(rc), OurVerdict::Ok(oc)) => {
                if rc == oc {
                    matched += 1;
                } else {
                    failures.push(format!(
                        "MISMATCH `{input_disp}`: reference `{rc}` vs ours `{oc}`"
                    ));
                }
            }
            (RefVerdict::Partial(rc), OurVerdict::Partial(oc)) => {
                if rc == oc {
                    matched += 1;
                } else {
                    failures.push(format!(
                        "MISMATCH (partial) `{input_disp}`: reference `{rc}` vs ours `{oc}`"
                    ));
                }
            }
            // Reference accepts, we are silent → coverage gap (safe).
            (
                RefVerdict::Ok(_) | RefVerdict::Partial(_),
                OurVerdict::Error | OurVerdict::Unsupported,
            ) => coverage_gap += 1,

            // Reference and ours disagree on consumption boundary → a wrong parse.
            (RefVerdict::Ok(rc), OurVerdict::Partial(oc)) => failures.push(format!(
                "BOUNDARY `{input_disp}`: reference fully parses `{rc}`, we stopped early at `{oc}`"
            )),
            (RefVerdict::Partial(rc), OurVerdict::Ok(oc)) => failures.push(format!(
                "BOUNDARY `{input_disp}`: reference partial `{rc}`, we consumed all as `{oc}`"
            )),
        }
    }

    let mut report = String::new();
    let _ = writeln!(report, "\n=== steins-phpdoc reference-corpus compatibility ===");
    let _ = writeln!(report, "total fixtures:      {total}");
    let _ = writeln!(
        report,
        "exact agreement:     {matched}  ({:.1}%)",
        100.0 * matched as f64 / total as f64
    );
    let _ = writeln!(report, "coverage gaps:       {coverage_gap}  (reference accepts, we are silent)");
    let _ = writeln!(report, "non-UTF-8 skipped:   {non_utf8}");
    let _ = writeln!(report, "wrong-parse failures:{}", failures.len());
    println!("{report}");

    if !failures.is_empty() {
        let mut msg = format!("{} wrong-parse disagreement(s):\n", failures.len());
        for f in &failures {
            let _ = writeln!(msg, "  - {f}");
        }
        panic!("{msg}\n{report}");
    }

    // Guard against silent regression of the ported grammar: we should match the
    // large majority of the corpus outright.
    assert!(
        matched * 100 >= total * 80,
        "subset coverage regressed: only {matched}/{total} exact matches"
    );
}

/// Split raw bytes into lines on `\n`, dropping a single trailing `\r` per line.
fn split_lines(bytes: &[u8]) -> Vec<&[u8]> {
    let mut lines = Vec::new();
    let mut start = 0;
    for i in 0..bytes.len() {
        if bytes[i] == b'\n' {
            let mut end = i;
            if end > start && bytes[end - 1] == b'\r' {
                end -= 1;
            }
            lines.push(&bytes[start..end]);
            start = i + 1;
        }
    }
    if start < bytes.len() {
        lines.push(&bytes[start..]);
    }
    lines
}
